/**
 * Buildings Database - Dubai Residential Properties
 * Imported from assetintel_complete_dubai_residential_database.csv
 * Includes tier classification and premium calculations
 */

export interface BuildingRecord {
  name: string;
  area: string;
  tier: "ultra-luxury" | "luxury" | "mid" | "low";
  premiumPercentage: number;
  dldKey?: string;   // normalized DLD dataset key → enables live Ejari lookup
  dldArea?: string;  // DLD administrative area (e.g. "Burj Khalifa")
}

// Map CSV tiers to our system with premium percentages
const mapTierAndPremium = (
  csvTier: "High" | "Medium" | "Low-to-Medium"
): { tier: "ultra-luxury" | "luxury" | "mid" | "low"; premiumPercentage: number } => {
  switch (csvTier) {
    case "High":
      // High tier = ultra-luxury/luxury with 1-2% premium
      return { tier: "luxury", premiumPercentage: 0.6 };
    case "Medium":
      // Medium tier = mid with 0.5-1% premium
      return { tier: "mid", premiumPercentage: 0.3 };
    case "Low-to-Medium":
      // Low-to-medium = low with 0% premium
      return { tier: "low", premiumPercentage: 0 };
    default:
      return { tier: "mid", premiumPercentage: 0.5 };
  }
};

// Outskirt areas for long-term rental suggestions
// "Town Square" and "JVT" are separate communities and are listed separately.
// They were previously collapsed into one "Town Square & JVT" label, which
// resolved to the TOWN SQUARE master for everything under it — harmless while
// only Town Square buildings used it, but silently wrong for any JVT building
// added later (JVT sits in Al Barsha South Fifth, Town Square in Al Yelayiss 2).
//
// NOTE for adding JVT buildings: set `area` to "Jumeirah Village Triangle (JVT)",
// the same shape as the JBR entries. A bare "JVT" is a single token and the
// master matcher deliberately refuses those as too collision-prone, so it would
// fall through to the pooled area figure instead of the JVT community.
export const OUTSKIRT_AREAS = ["Dubai South", "JVT", "Town Square", "DAMAC Hills 2"];

/**
 * Check if an area is considered an outskirt
 */
export const isOutskirtArea = (area: string): boolean => {
  const normalizedArea = area.toLowerCase().trim();
  return OUTSKIRT_AREAS.some((a) => normalizedArea.includes(a.toLowerCase()));
};

/**
 * Complete buildings database - all 600+ properties from CSV
 */
export const BUILDINGS_DATABASE: Record<string, BuildingRecord> = {
  // Dubai Marina (High tier)
  "Al Anbar Tower": {
    name: "Al Anbar Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Fairooz Tower": {
    name: "Al Fairooz Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Mass Tower": {
    name: "Al Mass Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Mesk Tower": {
    name: "Al Mesk Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Murjan Tower": {
    name: "Al Murjan Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Yass Tower": {
    name: "Al Yass Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Attessa Tower": {
    name: "Attessa Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Aurora Tower": {
    name: "Aurora Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Beauport Tower": {
    name: "Beauport Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Delphine Tower": {
    name: "Delphine Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Paloma Tower": {
    name: "Paloma Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Shemara Tower": {
    name: "Shemara Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Blakely Tower": {
    name: "Blakely Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bonaire Tower": {
    name: "Bonaire Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Fairfield Tower": {
    name: "Fairfield Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sanibel Tower": {
    name: "Sanibel Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Residences at Marina Gate 1": {
    name: "The Residences at Marina Gate 1",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "at marina gate 1",
    dldArea: "Marsa Dubai",
  },
  "The Residences at Marina Gate 2": {
    name: "The Residences at Marina Gate 2",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "at marina gate 2",
    dldArea: "Marsa Dubai",
  },
  "Marina Diamond 1": {
    name: "Marina Diamond 1",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Diamond 2": {
    name: "Marina Diamond 2",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Diamond 3": {
    name: "Marina Diamond 3",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Diamond 4": {
    name: "Marina Diamond 4",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Diamond 5": {
    name: "Marina Diamond 5",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Diamond 6": {
    name: "Marina Diamond 6",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Majara 1": {
    name: "Al Majara 1",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Majara 2": {
    name: "Al Majara 2",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Majara 3": {
    name: "Al Majara 3",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Majara 5": {
    name: "Al Majara 5",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Sahab 1": {
    name: "Al Sahab 1",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Sahab 2": {
    name: "Al Sahab 2",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Quays North": {
    name: "Marina Quays North",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "marina quays",
    dldArea: "Marsa Dubai",
  },
  "Marina Quays South": {
    name: "Marina Quays South",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "marina quays",
    dldArea: "Marsa Dubai",
  },
  "Marina Quays East": {
    name: "Marina Quays East",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "marina quays",
    dldArea: "Marsa Dubai",
  },
  "52|42 Tower 1": {
    name: "52|42 Tower 1",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "5242",
    dldArea: "Marsa Dubai",
  },
  "52|42 Tower 2": {
    name: "52|42 Tower 2",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "5242",
    dldArea: "Marsa Dubai",
  },
  "Silverene Tower A": {
    name: "Silverene Tower A",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "silverene",
    dldArea: "Marsa Dubai",
  },
  "Silverene Tower B": {
    name: "Silverene Tower B",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "silverene",
    dldArea: "Marsa Dubai",
  },
  "Sparkle Tower 1": {
    name: "Sparkle Tower 1",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "sparkle",
    dldArea: "Marsa Dubai",
  },
  "Sparkle Tower 2": {
    name: "Sparkle Tower 2",
    area: "Dubai Marina",
    ...mapTierAndPremium("High"),
    dldKey: "sparkle",
    dldArea: "Marsa Dubai",
  },
  "DEC Tower A": {
    name: "DEC Tower A",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "DEC Tower B": {
    name: "DEC Tower B",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Dream Tower 1": {
    name: "Dream Tower 1",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Dream Tower 2": {
    name: "Dream Tower 2",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina View Tower A": {
    name: "Marina View Tower A",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina View Tower B": {
    name: "Marina View Tower B",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Wharf 1": {
    name: "Marina Wharf 1",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Wharf 2": {
    name: "Marina Wharf 2",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Jewels Tower A": {
    name: "The Jewels Tower A",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Jewels Tower B": {
    name: "The Jewels Tower B",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bay Central West Tower": {
    name: "Bay Central West Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bay Central Central Tower": {
    name: "Bay Central Central Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Princess Tower": {
    name: "Princess Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "23 Marina": {
    name: "23 Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Elite Residence": {
    name: "Elite Residence",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Cayan Tower": {
    name: "Cayan Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "DAMAC Heights": {
    name: "DAMAC Heights",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Ocean Heights": {
    name: "Ocean Heights",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Torch": {
    name: "The Torch",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sulafa Tower": {
    name: "Sulafa Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Pinnacle": {
    name: "Marina Pinnacle",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Mag 218 Tower": {
    name: "Mag 218 Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Emirates Crown": {
    name: "Emirates Crown",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina 101": {
    name: "Marina 101",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Le Rêve": {
    name: "Le Rêve",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Stella Maris Tower": {
    name: "Stella Maris Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Studio One Tower": {
    name: "Studio One Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "No. 9 Tower": {
    name: "No. 9 Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "LIV Marina": {
    name: "LIV Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "LIV Residence": {
    name: "LIV Residence",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Botanica Tower": {
    name: "Botanica Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Heights Tower": {
    name: "Marina Heights Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Trident Grand Residence": {
    name: "Trident Grand Residence",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Trident Bayside": {
    name: "Trident Bayside",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Trident Marinascape Avant": {
    name: "Trident Marinascape Avant",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Trident Marinascape Oceanic": {
    name: "Trident Marinascape Oceanic",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Trident Waterfront": {
    name: "Trident Waterfront",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Waves Tower A": {
    name: "The Waves Tower A",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Waves Tower B": {
    name: "The Waves Tower B",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Horizon Tower": {
    name: "Horizon Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Dorra Bay": {
    name: "Dorra Bay",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Manchester Tower": {
    name: "Manchester Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Zumurud Tower": {
    name: "Zumurud Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Cascades": {
    name: "The Cascades",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Yacht Bay": {
    name: "Yacht Bay",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Time Place Tower": {
    name: "Time Place Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Skyview Tower": {
    name: "Skyview Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Arcade Tower": {
    name: "Marina Arcade Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Continental Tower": {
    name: "Continental Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Terrace": {
    name: "Marina Terrace",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Sail": {
    name: "Marina Sail",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Iris Blue": {
    name: "Iris Blue",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Orra Marina": {
    name: "Orra Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Orra Harbour Residences": {
    name: "Orra Harbour Residences",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "La Riviera Tower": {
    name: "La Riviera Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "ARY Marina View": {
    name: "ARY Marina View",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "JAM Marina Residence": {
    name: "JAM Marina Residence",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Point": {
    name: "The Point",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina First Tower": {
    name: "Marina First Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Ariyana Tower": {
    name: "Ariyana Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Westside Marina": {
    name: "Westside Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Park": {
    name: "Marina Park",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Azure": {
    name: "Azure",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Atlantic Dubai Marina": {
    name: "The Atlantic Dubai Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "KG Tower": {
    name: "KG Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Panoramic Tower": {
    name: "Panoramic Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Zen Tower": {
    name: "The Zen Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Durrat Al Marsa": {
    name: "Durrat Al Marsa",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Belvedere": {
    name: "The Belvedere",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Escan Marina Tower": {
    name: "Escan Marina Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Living": {
    name: "Marina Living",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Dubai Marina Moon Tower": {
    name: "Dubai Marina Moon Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Royal Oceanic": {
    name: "The Royal Oceanic",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "West Avenue Tower": {
    name: "West Avenue Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Star": {
    name: "Marina Star",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Pearl": {
    name: "Marina Pearl",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Royale Tower": {
    name: "Marina Royale Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Marina Mansions": {
    name: "Marina Mansions",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "La Residence Del Mar": {
    name: "La Residence Del Mar",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bunyan Tower": {
    name: "Bunyan Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Safeer Tower": {
    name: "Safeer Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Seef Tower": {
    name: "Al Seef Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Emerald Residence": {
    name: "Emerald Residence",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Habtoor Tower": {
    name: "Al Habtoor Tower",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Franck Muller Vanguard": {
    name: "Franck Muller Vanguard",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Six Senses Residences Dubai Marina": {
    name: "Six Senses Residences Dubai Marina",
    area: "Dubai Marina",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },

  // JBR (High tier)
  "Murjan 1": {
    name: "Murjan 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Murjan 2": {
    name: "Murjan 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Murjan 3": {
    name: "Murjan 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Murjan 4": {
    name: "Murjan 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Murjan 5": {
    name: "Murjan 5",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Murjan 6": {
    name: "Murjan 6",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 1": {
    name: "Sadaf 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 2": {
    name: "Sadaf 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 3": {
    name: "Sadaf 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 4": {
    name: "Sadaf 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 5": {
    name: "Sadaf 5",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 6": {
    name: "Sadaf 6",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 7": {
    name: "Sadaf 7",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Sadaf 8": {
    name: "Sadaf 8",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 1": {
    name: "Bahar 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 2": {
    name: "Bahar 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 3": {
    name: "Bahar 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 4": {
    name: "Bahar 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 5": {
    name: "Bahar 5",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Bahar 6": {
    name: "Bahar 6",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 1": {
    name: "Rimal 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 2": {
    name: "Rimal 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 3": {
    name: "Rimal 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 4": {
    name: "Rimal 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 5": {
    name: "Rimal 5",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Rimal 6": {
    name: "Rimal 6",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Amwaj 1": {
    name: "Amwaj 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Amwaj 2": {
    name: "Amwaj 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Amwaj 3": {
    name: "Amwaj 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Amwaj 4": {
    name: "Amwaj 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Shams 1": {
    name: "Shams 1",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Shams 2": {
    name: "Shams 2",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Shams 3": {
    name: "Shams 3",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Shams 4": {
    name: "Shams 4",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Bateen Residences": {
    name: "Al Bateen Residences",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "1 JBR": {
    name: "1 JBR",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "The Address Residences Jumeirah Resort + Spa (Residential Tower)": {
    name: "The Address Residences Jumeirah Resort + Spa (Residential Tower)",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Fattan Marine Towers (Tower A - Residential)": {
    name: "Al Fattan Marine Towers (Tower A - Residential)",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "Al Fattan Marine Towers (Tower B - Residential)": {
    name: "Al Fattan Marine Towers (Tower B - Residential)",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },
  "La Vie JBR": {
    name: "La Vie JBR",
    area: "Jumeirah Beach Residence (JBR)",
    dldArea: "Marsa Dubai",
    ...mapTierAndPremium("High"),
  },

  // Downtown Dubai (High tier)
  "Burj Khalifa (Residential Wing)": {
    name: "Burj Khalifa (Residential Wing)",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Opera Grand": {
    name: "Opera Grand",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Il Primo": {
    name: "Il Primo",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Grande": {
    name: "Grande",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Forte Tower 1": {
    name: "Forte Tower 1",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "forte",
    dldArea: "Burj Khalifa",
  },
  "Forte Tower 2": {
    name: "Forte Tower 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "forte",
    dldArea: "Burj Khalifa",
  },
  "Act One": {
    name: "Act One",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "act one act two",
    dldArea: "Burj Khalifa",
  },
  "Act Two": {
    name: "Act Two",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "act one act two",
    dldArea: "Burj Khalifa",
  },
  "Burj Crown": {
    name: "Burj Crown",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Burj Royale": {
    name: "Burj Royale",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 1": {
    name: "The Residences 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 2": {
    name: "The Residences 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 3": {
    name: "The Residences 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 4": {
    name: "The Residences 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 5": {
    name: "The Residences 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 6": {
    name: "The Residences 6",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 7": {
    name: "The Residences 7",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 8": {
    name: "The Residences 8",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Residences 9": {
    name: "The Residences 9",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 1": {
    name: "South Ridge 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 2": {
    name: "South Ridge 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 3": {
    name: "South Ridge 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 4": {
    name: "South Ridge 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 5": {
    name: "South Ridge 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "South Ridge 6": {
    name: "South Ridge 6",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Burj Views Tower A": {
    name: "Burj Views Tower A",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "burj views",
    dldArea: "Burj Khalifa",
  },
  "Burj Views Tower B": {
    name: "Burj Views Tower B",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "burj views",
    dldArea: "Burj Khalifa",
  },
  "Burj Views Tower C": {
    name: "Burj Views Tower C",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "burj views",
    dldArea: "Burj Khalifa",
  },
  "The Lofts East": {
    name: "The Lofts East",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Lofts West": {
    name: "The Lofts West",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "The Lofts Central": {
    name: "The Lofts Central",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Boulevard Central 1": {
    name: "Boulevard Central 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Boulevard Central 2": {
    name: "Boulevard Central 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Claren Tower 1": {
    name: "Claren Tower 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Claren Tower 2": {
    name: "Claren Tower 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Boulevard Heights Tower 1": {
    name: "Boulevard Heights Tower 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Boulevard Heights Tower 2": {
    name: "Boulevard Heights Tower 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Burj Vista Tower 1": {
    name: "Burj Vista Tower 1",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "burj vista",
    dldArea: "Burj Khalifa",
  },
  "Burj Vista Tower 2": {
    name: "Burj Vista Tower 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "burj vista",
    dldArea: "Burj Khalifa",
  },
  "Standpoint Tower A": {
    name: "Standpoint Tower A",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Standpoint Tower B": {
    name: "Standpoint Tower B",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Bellevue Towers Tower 1": {
    name: "Bellevue Towers Tower 1",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "bellevue",
    dldArea: "Burj Khalifa",
  },
  "Bellevue Towers Tower 2": {
    name: "Bellevue Towers Tower 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "bellevue",
    dldArea: "Burj Khalifa",
  },
  "Address Residences Dubai Opera Tower 1": {
    name: "Address Residences Dubai Opera Tower 1",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "address dubai opera",
    dldArea: "Burj Khalifa",
  },
  "Address Residences Dubai Opera Tower 2": {
    name: "Address Residences Dubai Opera Tower 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "address dubai opera",
    dldArea: "Burj Khalifa",
  },
  "Address Residences Downtown (Residential Wing)": {
    name: "Address Residences Downtown (Residential Wing)",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Address Residences Boulevard (Residential Wing)": {
    name: "Address Residences Boulevard (Residential Wing)",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Address Residences Sky View (Residential Wing)": {
    name: "Address Residences Sky View (Residential Wing)",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Address Fountain Views 1": {
    name: "Address Fountain Views 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Address Fountain Views 2": {
    name: "Address Fountain Views 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Address Fountain Views 3": {
    name: "Address Fountain Views 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Vida Residences Downtown": {
    name: "Vida Residences Downtown",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Vida Dubai Mall Tower 1": {
    name: "Vida Dubai Mall Tower 1",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "vida dubai mall",
    dldArea: "Burj Khalifa",
  },
  "Vida Dubai Mall Tower 2": {
    name: "Vida Dubai Mall Tower 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "vida dubai mall",
    dldArea: "Burj Khalifa",
  },
  "St. Regis The Residences Tower 1": {
    name: "St. Regis The Residences Tower 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "St. Regis The Residences Tower 2": {
    name: "St. Regis The Residences Tower 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "DT1": {
    name: "DT1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Elite Downtown Residence": {
    name: "Elite Downtown Residence",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Elite 1 Downtown Residence": {
    name: "Elite 1 Downtown Residence",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Elite Downtown Residence 2": {
    name: "Elite Downtown Residence 2",
    area: "Downtown Dubai",
    ...mapTierAndPremium("High"),
    dldKey: "elite downtown",
    dldArea: "Burj Khalifa",
  },
  "Al Noujoum Tower": {
    name: "Al Noujoum Tower",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "City Center Residences": {
    name: "City Center Residences",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Society House": {
    name: "Society House",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Fairmont Residences Solara Tower": {
    name: "Fairmont Residences Solara Tower",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Mercedes-Benz Places by Binghatti": {
    name: "Mercedes-Benz Places by Binghatti",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Miska 1": {
    name: "Miska 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Miska 2": {
    name: "Miska 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Miska 3": {
    name: "Miska 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Miska 4": {
    name: "Miska 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Miska 5": {
    name: "Miska 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zanzebeel 1": {
    name: "Zanzebeel 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zanzebeel 2": {
    name: "Zanzebeel 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zanzebeel 3": {
    name: "Zanzebeel 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zanzebeel 4": {
    name: "Zanzebeel 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 1": {
    name: "Reehan 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 2": {
    name: "Reehan 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 3": {
    name: "Reehan 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 4": {
    name: "Reehan 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 5": {
    name: "Reehan 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Reehan 6": {
    name: "Reehan 6",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Kamoon 1": {
    name: "Kamoon 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Kamoon 2": {
    name: "Kamoon 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Kamoon 3": {
    name: "Kamoon 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Kamoon 4": {
    name: "Kamoon 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Yansoon 1": {
    name: "Yansoon 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Yansoon 2": {
    name: "Yansoon 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Yansoon 3": {
    name: "Yansoon 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Yansoon 4": {
    name: "Yansoon 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Yansoon 5": {
    name: "Yansoon 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zaafaran 1": {
    name: "Zaafaran 1",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zaafaran 2": {
    name: "Zaafaran 2",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zaafaran 3": {
    name: "Zaafaran 3",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zaafaran 4": {
    name: "Zaafaran 4",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Zaafaran 5": {
    name: "Zaafaran 5",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Dunya Tower": {
    name: "Dunya Tower",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },
  "Tajer Residences": {
    name: "Tajer Residences",
    area: "Downtown Dubai",
    dldArea: "Burj Khalifa",
    ...mapTierAndPremium("High"),
  },

  // JVC (Low-to-Medium tier)
  "G-24": {
    name: "G-24",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Belgravia I": {
    name: "Belgravia I",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "belgravia",
    dldArea: "Al Barsha South Fourth",
  },
  "Belgravia II": {
    name: "Belgravia II",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "belgravia",
    dldArea: "Al Barsha South Fourth",
  },
  "Belgravia III": {
    name: "Belgravia III",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "belgravia iii",
    dldArea: "Al Barsha South Fourth",
  },
  "Belgravia Square": {
    name: "Belgravia Square",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "belgravia square",
    dldArea: "Al Barsha South Fourth",
  },
  "The Portman by Ellington": {
    name: "The Portman by Ellington",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Hillmont Residences": {
    name: "Hillmont Residences",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Eaton Place": {
    name: "Eaton Place",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Harrington House": {
    name: "Harrington House",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Oxford Residence 1": {
    name: "Oxford Residence 1",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "oxford",
    dldArea: "Al Barsha South Fourth",
  },
  "Oxford Residence 2": {
    name: "Oxford Residence 2",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "oxford 2",
    dldArea: "Al Barsha South Fourth",
  },
  "Oxford Boulevard": {
    name: "Oxford Boulevard",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Oxford Terraces": {
    name: "Oxford Terraces",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Oxford 212": {
    name: "Oxford 212",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Westwood Grande by Imtiaz": {
    name: "Westwood Grande by Imtiaz",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Pearl House by Imtiaz": {
    name: "Pearl House by Imtiaz",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Luma 22 by TownX": {
    name: "Luma 22 by TownX",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Luma Park Views": {
    name: "Luma Park Views",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bloom Towers (Tower A)": {
    name: "Bloom Towers (Tower A)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bloom Towers (Tower B)": {
    name: "Bloom Towers (Tower B)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bloom Towers (Tower C)": {
    name: "Bloom Towers (Tower C)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bloom Heights (Tower A)": {
    name: "Bloom Heights (Tower A)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bloom Heights (Tower B)": {
    name: "Bloom Heights (Tower B)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Zaya Hameni": {
    name: "Zaya Hameni",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Reef Residence": {
    name: "Reef Residence",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Ghalia Constella by DAMAC": {
    name: "Ghalia Constella by DAMAC",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Tower 108 by DAMAC": {
    name: "Tower 108 by DAMAC",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "O2 Tower": {
    name: "O2 Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Park View Tower": {
    name: "Park View Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Regina Tower": {
    name: "Regina Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Sydney Tower": {
    name: "Sydney Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Dana Tower": {
    name: "Dana Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Al Dana Tower": {
    name: "Al Dana Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Plaza Residences (Tower A)": {
    name: "Plaza Residences (Tower A)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Plaza Residences (Tower B)": {
    name: "Plaza Residences (Tower B)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Plaza Residences (Tower C)": {
    name: "Plaza Residences (Tower C)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Kensington Manor": {
    name: "Kensington Manor",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Astoria Residence": {
    name: "Astoria Residence",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Alcove Residences": {
    name: "Alcove Residences",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Aces Chateau": {
    name: "Aces Chateau",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Le Grand Chateau": {
    name: "Le Grand Chateau",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti House": {
    name: "Binghatti House",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Luna": {
    name: "Binghatti Luna",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Amber": {
    name: "Binghatti Amber",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Crest": {
    name: "Binghatti Crest",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Heights": {
    name: "Binghatti Heights",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Gardenia": {
    name: "Binghatti Gardenia",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Orchid": {
    name: "Binghatti Orchid",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Aurora": {
    name: "Binghatti Aurora",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Binghatti Circle": {
    name: "Binghatti Circle",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Serenity Lakes by Binghatti": {
    name: "Serenity Lakes by Binghatti",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Elitz by Danube (Tower 1)": {
    name: "Elitz by Danube (Tower 1)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Elitz by Danube (Tower 2)": {
    name: "Elitz by Danube (Tower 2)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Eleganz by Danube": {
    name: "Eleganz by Danube",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "La Riviera Apartments": {
    name: "La Riviera Apartments",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Hyati Residences": {
    name: "Hyati Residences",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Signature Livings (Solar Powered)": {
    name: "Signature Livings (Solar Powered)",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Pantheon Elysee I": {
    name: "Pantheon Elysee I",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "pantheon elysee",
    dldArea: "Al Barsha South Fourth",
  },
  "Pantheon Elysee II": {
    name: "Pantheon Elysee II",
    area: "Jumeirah Village Circle (JVC)",
    ...mapTierAndPremium("Low-to-Medium"),
    dldKey: "pantheon elysee",
    dldArea: "Al Barsha South Fourth",
  },
  "Elysee Heights": {
    name: "Elysee Heights",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Torino by ORO24": {
    name: "Torino by ORO24",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Samana Waves": {
    name: "Samana Waves",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Samana Park Views": {
    name: "Samana Park Views",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Loci Residences": {
    name: "Loci Residences",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "The Autograph": {
    name: "The Autograph",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Avanos Building": {
    name: "Avanos Building",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Bluebell Residence": {
    name: "Bluebell Residence",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Emerald Tower": {
    name: "Emerald Tower",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Lolena Residence": {
    name: "Lolena Residence",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Tasmeer Residence": {
    name: "Tasmeer Residence",
    area: "Jumeirah Village Circle (JVC)",
    dldArea: "Al Barsha South Fourth",
    ...mapTierAndPremium("Low-to-Medium"),
  },

  // Business Bay (Medium tier)
  "Executive Towers Tower B": {
    name: "Executive Towers Tower B",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower C": {
    name: "Executive Towers Tower C",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower J": {
    name: "Executive Towers Tower J",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower M": {
    name: "Executive Towers Tower M",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower K": {
    name: "Executive Towers Tower K",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower L": {
    name: "Executive Towers Tower L",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower G": {
    name: "Executive Towers Tower G",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower H": {
    name: "Executive Towers Tower H",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower D": {
    name: "Executive Towers Tower D",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower E": {
    name: "Executive Towers Tower E",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Executive Towers Tower F": {
    name: "Executive Towers Tower F",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Capital Bay Tower A": {
    name: "Capital Bay Tower A",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Capital Bay Tower B": {
    name: "Capital Bay Tower B",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Capital Bay Tower C": {
    name: "Capital Bay Tower C",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Al Habtoor City Noora Tower": {
    name: "Al Habtoor City Noora Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Al Habtoor City Amna Tower": {
    name: "Al Habtoor City Amna Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Al Habtoor City Meera Tower": {
    name: "Al Habtoor City Meera Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Paramount Towers Tower A": {
    name: "Paramount Towers Tower A",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Paramount Towers Tower B": {
    name: "Paramount Towers Tower B",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Paramount Towers Tower C": {
    name: "Paramount Towers Tower C",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Tiara United Tower 1": {
    name: "Tiara United Tower 1",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Tiara United Tower 2": {
    name: "Tiara United Tower 2",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "The Atria (Residential Tower)": {
    name: "The Atria (Residential Tower)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Sol Bay": {
    name: "Sol Bay",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Churchill Residence": {
    name: "Churchill Residence",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "The Opus by Omniyat (Residential Wing)": {
    name: "The Opus by Omniyat (Residential Wing)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Bugatti Residences by Binghatti": {
    name: "Bugatti Residences by Binghatti",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Burj Binghatti Jacob & Co Residences": {
    name: "Burj Binghatti Jacob & Co Residences",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Bayz 101 by Danube": {
    name: "Bayz 101 by Danube",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Regalia by Deyaar": {
    name: "Regalia by Deyaar",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Urban Oasis by Missoni": {
    name: "Urban Oasis by Missoni",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Vera Residences": {
    name: "Vera Residences",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Prive by Damac (Tower A)": {
    name: "Prive by Damac (Tower A)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Prive by Damac (Tower B)": {
    name: "Prive by Damac (Tower B)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Damac Towers by Paramount (Residences Wing)": {
    name: "Damac Towers by Paramount (Residences Wing)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Marquise Square Tower": {
    name: "Marquise Square Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "The Pad by Omniyat": {
    name: "The Pad by Omniyat",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Bayswater (Residential Units)": {
    name: "Bayswater (Residential Units)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Clayton Residency": {
    name: "Clayton Residency",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Mayfair Residency": {
    name: "Mayfair Residency",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Hamilton Residency": {
    name: "Hamilton Residency",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Windsor Manor": {
    name: "Windsor Manor",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Merano Tower": {
    name: "Merano Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Avanti Tower": {
    name: "Avanti Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Reva Residences": {
    name: "Reva Residences",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Zada Residences": {
    name: "Zada Residences",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Scala Tower": {
    name: "Scala Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Fairview Residency": {
    name: "Fairview Residency",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "The Sterling East Tower": {
    name: "The Sterling East Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "The Sterling West Tower": {
    name: "The Sterling West Tower",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Peninsula Five": {
    name: "Peninsula Five",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Peninsula Four (The Plaza)": {
    name: "Peninsula Four (The Plaza)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Peninsula One": {
    name: "Peninsula One",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Peninsula Two": {
    name: "Peninsula Two",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Peninsula Three": {
    name: "Peninsula Three",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Canal Crown by DAMAC": {
    name: "Canal Crown by DAMAC",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Damac Maison Privé": {
    name: "Damac Maison Privé",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Jone Residences": {
    name: "Jone Residences",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },
  "Grosvenor Business Bay (Residential Component)": {
    name: "Grosvenor Business Bay (Residential Component)",
    area: "Business Bay",
    dldArea: "Business Bay",
    ...mapTierAndPremium("Medium"),
  },

  // Palm Jumeirah (High tier)
  "Shoreline Apartments 1 (Al Basri)": {
    name: "Shoreline Apartments 1 (Al Basri)",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "Golden Mile 1": {
    name: "Golden Mile 1",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "Marina Residences 1": {
    name: "Marina Residences 1",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "Oceana Adriatic": {
    name: "Oceana Adriatic",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "Tiara Aquamarine": {
    name: "Tiara Aquamarine",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "The Palm Tower (Residential Wing)": {
    name: "The Palm Tower (Residential Wing)",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },
  "One Palm by Omniyat": {
    name: "One Palm by Omniyat",
    area: "Palm Jumeirah",
    dldArea: "Palm Jumeirah",
    ...mapTierAndPremium("High"),
  },

  // Creek Harbour (High tier)
  "Creek Horizon Tower 1": {
    name: "Creek Horizon Tower 1",
    area: "Dubai Creek Harbour",
    ...mapTierAndPremium("High"),
    dldKey: "creek horizon",
    dldArea: "Al Khairan First",
  },
  "Address Grand Creek Residences": {
    name: "Address Grand Creek Residences",
    area: "Dubai Creek Harbour",
    dldArea: "Al Khairan First",
    ...mapTierAndPremium("High"),
  },

  // Dubai Hills Estate (Medium tier)
  "Park Heights 1": {
    name: "Park Heights 1",
    area: "Dubai Hills Estate",
    dldArea: "Hadaeq Sheikh Mohammed Bin Rashid",
    ...mapTierAndPremium("Medium"),
  },
  "Park Heights 2": {
    name: "Park Heights 2",
    area: "Dubai Hills Estate",
    dldArea: "Hadaeq Sheikh Mohammed Bin Rashid",
    ...mapTierAndPremium("Medium"),
  },

  // Town Square (Low-to-Medium tier)
  "Zahra Apartments": {
    name: "Zahra Apartments",
    area: "Town Square",
    dldArea: "Al Yelayiss 2",
    ...mapTierAndPremium("Low-to-Medium"),
  },
  "Nshama Town Square Shams": {
    name: "Nshama Town Square Shams",
    area: "Town Square",
    dldArea: "Al Yelayiss 2",
    ...mapTierAndPremium("Low-to-Medium"),
  },
};

/**
 * Get all buildings sorted by area
 */
export const getBuildingsByArea = (area: string): BuildingRecord[] => {
  return Object.values(BUILDINGS_DATABASE).filter((b) => b.area === area);
};

/**
 * Get all unique areas
 */
export const getAllAreas = (): string[] => {
  const areas = new Set(Object.values(BUILDINGS_DATABASE).map((b) => b.area));
  return Array.from(areas).sort();
};

/**
 * Get building by name
 */
export const getBuildingByName = (name: string): BuildingRecord | undefined => {
  return BUILDINGS_DATABASE[name];
};
