/**
 * DDA (Dubai Data Authority) API client — server-side only.
 * Manages OAuth2 token caching and provides a typed fetch helper
 * for the data.dubai open API.
 */

import nameMapData from "./data/dld-name-map.json";

// ── DLD canonical name map ─────────────────────────────────────────────────
// Maps our normalized building keys → official DLD project_name_en values.
// Generated by scripts/build-dld-name-map.mjs from dld_units-open-api.
const DLD_NAME_MAP: Record<string, string> = (nameMapData as { mapping: Record<string, string> }).mapping;

// Mirrors normalize() in building-rents.ts — must stay in sync
function _normalize(name: string): string {
  return String(name ?? "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\b(tower|towers|residence|residences|building|bldg|apartment|apartments|the)\b/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Returns the official DLD project_name_en for a display name, or null.
 * Tries the full normalized key first, then progressively strips trailing
 * tokens to handle tower/phase suffixes (e.g. "BLVD CRESCENT TOWER 1" → "blvd crescent 1" → "blvd crescent").
 */
export function resolveDLDName(displayName: string): string | null {
  if (!displayName) return null;
  let key = _normalize(displayName);
  while (key.length >= 4) {
    const mapped = DLD_NAME_MAP[key];
    if (mapped) return mapped;
    const shorter = key.replace(/\s+\S+$/, "").trim();
    if (shorter === key) break;
    key = shorter;
  }
  return null;
}

// ── Token cache (process-level, survives hot-reload in dev) ───────────────
let cachedToken: string | null = null;
let tokenExpiresAt = 0; // epoch ms

async function getToken(): Promise<string> {
  if (cachedToken && Date.now() < tokenExpiresAt) return cachedToken;

  const base   = (process.env.DDA_BASE_URL        ?? "").trim();
  const appId  = (process.env.DDA_APP_IDENTIFIER  ?? "").trim();
  const cid    = (process.env.DDA_CLIENT_ID       ?? "").trim();
  const secret = (process.env.DDA_CLIENT_SECRET   ?? "").trim();

  if (!base || !appId || !cid || !secret) throw new Error("DDA env vars not configured");

  const res = await fetch(
    `${base}/secure/ssis/dubaiai/gatewaytoken/1.0.0/getAccessToken`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        "x-DDA-SecurityApplicationIdentifier": appId,
      },
      body: new URLSearchParams({ grant_type: "client_credentials", client_id: cid, client_secret: secret }).toString(),
      signal: AbortSignal.timeout(15_000),
    }
  );

  if (!res.ok) throw new Error(`DDA token fetch failed: ${res.status}`);
  const data = await res.json();
  if (!data.access_token) throw new Error("DDA token response missing access_token");

  cachedToken = data.access_token;
  // Refresh 5 minutes before actual expiry (expires_in is in seconds, default 3600)
  tokenExpiresAt = Date.now() + ((data.expires_in ?? 3600) - 300) * 1000;
  return cachedToken!;
}

// ── Raw query ──────────────────────────────────────────────────────────────

export interface DDAQueryOptions {
  entity: string;
  dataset: string;
  page?: number;
  pageSize?: number;
  /** Exact-match filters: column=value (values are single-quoted so spaces are safe) */
  filters?: Record<string, string>;
  /** LIKE filters: column LIKE 'pattern' (caller provides the pattern including % wildcards) */
  likeFilters?: Record<string, string>;
  columns?: string[];
  orderBy?: string;
  orderDir?: "asc" | "desc";
}

export async function ddaQuery<T = Record<string, unknown>>(
  opts: DDAQueryOptions
): Promise<{ results: T[]; total: number }> {
  const base  = (process.env.DDA_BASE_URL ?? "").trim();
  const token = await getToken();

  const url = new URL(`${base}/open/${opts.entity}/${opts.dataset}`);
  if (opts.page)     url.searchParams.set("page",     String(opts.page));
  if (opts.pageSize) url.searchParams.set("pageSize", String(opts.pageSize));
  if (opts.columns?.length) url.searchParams.set("column", opts.columns.join(","));
  if (opts.orderBy)  url.searchParams.set("order_by",  opts.orderBy);
  if (opts.orderDir) url.searchParams.set("order_dir", opts.orderDir);

  // Exact-match: filter=col='value' — single quotes required when value contains spaces
  if (opts.filters) {
    for (const [col, val] of Object.entries(opts.filters)) {
      url.searchParams.append("filter", `${col}='${val}'`);
    }
  }
  // LIKE: filter=col LIKE 'pattern'
  if (opts.likeFilters) {
    for (const [col, val] of Object.entries(opts.likeFilters)) {
      url.searchParams.append("filter", `${col} LIKE '${val}'`);
    }
  }

  const res = await fetch(url.toString(), {
    headers: { Authorization: `Bearer ${token}` },
    signal: AbortSignal.timeout(25_000),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`DDA query failed: ${res.status} ${body.slice(0, 200)}`);
  }

  const json = await res.json();
  const results: T[] = json.results ?? json.data ?? json.records ?? [];
  const total: number = json.total ?? json.count ?? results.length;
  return { results, total };
}

// ── DLD Rent Contract record (key fields only) ─────────────────────────────

export interface DLDRentContract {
  contract_id: string;
  annual_amount: number;
  actual_area: number;
  project_name_en: string;
  area_name_en: string;
  ejari_property_type_en: string;
  ejari_property_sub_type_en: string;  // e.g. "Studio", "1 bed room+hall"
  property_usage_en: string;            // "Residential", "Commercial" …
  contract_start_date: string;          // "YYYY-MM-DD"
  contract_end_date: string;
  is_free_hold: number;
  contract_reg_type_en: string;         // "New" | "Renew"
}

// ── Bedroom type normaliser (matches ingest-dld-rents.mjs logic) ──────────

/** Map DLD ejari_property_sub_type_en → our UnitSize bucket */
export function dldBedroomBucket(subType: string, propType?: string): string | null {
  const r = String(subType ?? "").toLowerCase();
  const t = String(propType ?? "").toLowerCase();
  if (r.includes("studio")) return "STU";
  const m = r.match(/(\d+)\s*bed/);
  const beds = m ? parseInt(m[1], 10) : null;
  if (beds === null) return null;
  const isVilla = t.includes("villa") || t.includes("townhouse");
  if (!isVilla) {
    if (beds <= 1) return "1BR";
    if (beds === 2) return "2BR";
    if (beds === 3) return "3BR";
    return beds + "BR";
  }
  return null; // skip villas for residential LTR benchmarking
}

// ── Building age / completion lookup ────────────────────────────────────────
// Joins dld_units-open-api (project_name_en → project_id) with
// dld_projects-open-api (project_id → completion_date / status) since the
// projects dataset only exposes the Arabic project name.

interface DLDUnitProjectRow {
  project_id: number;
  project_name_en: string;
  master_project_en: string;
}

interface DLDProjectRow {
  project_id: number;
  project_status: string;         // ACTIVE | FINISHED | PENDING | CANCELLED
  percent_completed: number;
  completion_date: string | null; // actual (FINISHED) or estimated handover (ACTIVE)
  project_start_date: string | null;
  no_of_buildings: number;
  no_of_units: number;
}

export interface BuildingAgeResult {
  matched: boolean;
  projectNameDLD: string | null;
  projectStatus: string | null;
  completionDate: string | null;
  completionYear: number | null;
  ageYears: number | null;        // null if not yet completed
  percentCompleted: number | null;
  projectStartDate: string | null;
}

const NOT_FOUND: BuildingAgeResult = {
  matched: false, projectNameDLD: null, projectStatus: null, completionDate: null,
  completionYear: null, ageYears: null, percentCompleted: null, projectStartDate: null,
};

/** Look up a building's completion/handover data via project_name_en (exact DLD name). */
export async function fetchBuildingAge(projectNameEn: string): Promise<BuildingAgeResult> {
  if (!projectNameEn) return NOT_FOUND;

  // 1. Resolve project_id from the units dataset (has English project names).
  let unitRows = (await ddaQuery<DLDUnitProjectRow>({
    entity: "dld",
    dataset: "dld_units-open-api",
    filters: { project_name_en: projectNameEn },
    columns: ["project_id", "project_name_en", "master_project_en"],
    pageSize: 1,
  })).results;

  if (!unitRows.length) {
    unitRows = (await ddaQuery<DLDUnitProjectRow>({
      entity: "dld",
      dataset: "dld_units-open-api",
      likeFilters: { project_name_en: `${projectNameEn}%` },
      columns: ["project_id", "project_name_en", "master_project_en"],
      pageSize: 1,
    })).results;
  }

  const projectId = unitRows[0]?.project_id;
  if (!projectId) return NOT_FOUND;

  // 2. Pull completion data from the projects dataset by project_id.
  const { results: projectRows } = await ddaQuery<DLDProjectRow>({
    entity: "dld",
    dataset: "dld_projects-open-api",
    filters: { project_id: String(projectId) },
    pageSize: 1,
  });

  const p = projectRows[0];
  if (!p) return NOT_FOUND;

  const completionYear = p.completion_date ? parseInt(p.completion_date.slice(0, 4), 10) : null;
  const isFinished = p.project_status === "FINISHED";
  const ageYears = isFinished && completionYear
    ? new Date().getFullYear() - completionYear
    : null;

  return {
    matched: true,
    projectNameDLD: unitRows[0]?.project_name_en ?? null,
    projectStatus: p.project_status ?? null,
    completionDate: p.completion_date ?? null,
    completionYear,
    ageYears,
    percentCompleted: p.percent_completed ?? null,
    projectStartDate: p.project_start_date ?? null,
  };
}

// ── Stats helpers ──────────────────────────────────────────────────────────

function median(sorted: number[]): number {
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : Math.round((sorted[mid - 1] + sorted[mid]) / 2);
}

function percentile(sorted: number[], p: number): number {
  const idx = (p / 100) * (sorted.length - 1);
  const lo = Math.floor(idx), hi = Math.ceil(idx);
  return Math.round(sorted[lo] + (sorted[hi] - sorted[lo]) * (idx - lo));
}

export interface LTRStat {
  median: number;
  p25: number;
  p75: number;
  n: number;
  aedPerSqft?: number;
  medianSqft?: number;
  asOf: string;
  source: "dda-live";
}

/** Compute LTR stats from an array of rent contract records. */
export function computeLTRStats(contracts: DLDRentContract[]): LTRStat | null {
  const rents = contracts
    .map(c => c.annual_amount)
    .filter(v => v > 5_000 && v < 5_000_000) // sanity bounds
    .sort((a, b) => a - b);

  if (rents.length < 3) return null;

  // actual_area is in sq.m. — convert to sqft for display; filter out junk (< 15 sqm = 161 sqft)
  const areasSqft = contracts
    .map(c => c.actual_area)
    .filter(v => v > 15 && v < 5_000)
    .map(v => Math.round(v * 10.764));
  const latestDate = contracts
    .map(c => c.contract_start_date)
    .filter(Boolean)
    .sort()
    .at(-1)
    ?.slice(0, 7) ?? "";

  const medianRent = median(rents);
  const medianSqft = areasSqft.length ? median([...areasSqft].sort((a, b) => a - b)) : undefined;

  return {
    median: medianRent,
    p25:    percentile(rents, 25),
    p75:    percentile(rents, 75),
    n:      rents.length,
    aedPerSqft: medianSqft ? Math.round(medianRent / medianSqft) : undefined,
    medianSqft,
    asOf:   latestDate,
    source: "dda-live",
  };
}

/**
 * Generate DLD name variants to try in sequence.
 * DLD stores names in ALL CAPS. Common mismatches:
 *   - BLVD ↔ BOULEVARD
 *   - "AT NAME" prefix added/missing in DLD
 *   - Trailing number stripped from group search
 */
function buildDLDVariants(displayName: string): string[] {
  const upper = displayName.toUpperCase().trim();
  const variants = new Set<string>();

  variants.add(upper);

  // Abbreviation: BOULEVARD ↔ BLVD
  const withBlvd = upper.replace(/\bBOULEVARD\b/g, "BLVD");
  const withBoulevard = upper.replace(/\bBLVD\b/g, "BOULEVARD");
  if (withBlvd !== upper) variants.add(withBlvd);
  if (withBoulevard !== upper) variants.add(withBoulevard);

  // "AT <NAME>" — DLD sometimes prefixes with AT
  variants.add(`AT ${upper}`);

  // Strip "BY <DEVELOPER>" suffix DLD may not store
  const withoutBy = upper.replace(/\s+BY\s+\S+.*$/, "").trim();
  if (withoutBy !== upper && withoutBy.length >= 4) variants.add(withoutBy);

  // Strip trailing single token (phase number, letter) for group match
  const withoutSuffix = upper.replace(/\s+\S+$/, "").trim();
  if (withoutSuffix !== upper && withoutSuffix.length >= 5) variants.add(withoutSuffix);

  return [...variants];
}

async function fetchContractsForName(
  dldName: string,
  columns: string[],
  cutoffStr: string,
  pageSize: number,
  maxRecords: number,
  exactMatch = false  // true when using canonical DLD name from name map
): Promise<DLDRentContract[]> {
  const allContracts: DLDRentContract[] = [];
  let page = 1;

  while (allContracts.length < maxRecords) {
    const { results } = await ddaQuery<DLDRentContract>({
      entity:      "dld",
      dataset:     "dld_rent_contracts-open-api",
      page,
      pageSize,
      columns,
      // Exact match for canonical names (faster, more precise)
      // LIKE prefix for variants to catch phase-numbered sub-buildings
      ...(exactMatch
        ? { filters:     { project_name_en: dldName } }
        : { likeFilters: { project_name_en: `${dldName}%` } }
      ),
      orderBy:     "contract_start_date",
      orderDir:    "desc",
    });

    if (!results.length) break;

    const recent = results.filter(c => {
      if (c.contract_start_date < cutoffStr) return false;
      if (!(c.property_usage_en?.toLowerCase().includes("resid") ?? true)) return false;
      // New contracts only — exclude renewals
      if (c.contract_reg_type_en && c.contract_reg_type_en !== "New") return false;
      // 1-year leases only — exclude multi-year (allow up to 13 months for rounding)
      if (c.contract_start_date && c.contract_end_date) {
        const start = new Date(c.contract_start_date);
        const end   = new Date(c.contract_end_date);
        const days  = (end.getTime() - start.getTime()) / 86_400_000;
        if (days > 400) return false;
      }
      return true;
    });
    allContracts.push(...recent);

    if (results.length < pageSize) break;
    page++;
  }

  return allContracts;
}

/** Fetch all rent contracts for a project name, optionally filtered by date window. */
export async function fetchProjectContracts(
  projectName: string,
  options: { daysBack?: number; maxRecords?: number } = {}
): Promise<DLDRentContract[]> {
  const { daysBack = 30, maxRecords = 2000 } = options;

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysBack);
  const cutoffStr = cutoff.toISOString().slice(0, 10);

  const columns: (keyof DLDRentContract)[] = [
    "contract_id", "annual_amount", "actual_area",
    "project_name_en", "area_name_en",
    "ejari_property_type_en", "ejari_property_sub_type_en",
    "property_usage_en", "contract_start_date", "contract_end_date", "is_free_hold",
    "contract_reg_type_en",
  ];

  // 1. Try the canonical DLD name — exact first, then LIKE (DLD sometimes stores trailing spaces)
  const canonicalName = resolveDLDName(projectName);
  if (canonicalName) {
    const exact = await fetchContractsForName(
      canonicalName, columns as string[], cutoffStr, 1000, maxRecords, true
    );
    if (exact.length > 0) return exact;

    // Exact returned 0 — try LIKE in case DLD stored name has trailing space/suffix
    const like = await fetchContractsForName(
      canonicalName, columns as string[], cutoffStr, 1000, maxRecords, false
    );
    if (like.length > 0) return like;
  }

  // 2. Try name variants (LIKE prefix) as fallback for unmapped buildings
  const variants = buildDLDVariants(projectName);
  for (const variant of variants) {
    // Skip if this variant is the same as canonical (already tried both ways)
    if (canonicalName && variant.toUpperCase() === canonicalName.toUpperCase()) continue;
    const contracts = await fetchContractsForName(
      variant, columns as string[], cutoffStr, 1000, maxRecords
    );
    if (contracts.length > 0) return contracts;
  }

  return [];
}

// ── Sale transactions (dld_transactions-open-api) ──────────────────────────

export interface DLDSaleTransaction {
  transaction_id: string;
  instance_date: string;          // "YYYY-MM-DD"
  trans_group_en: string;         // "Sales" | "Mortgages" | "Gifts" ...
  procedure_name_en: string;      // "Sell - Pre registration" | "Sell" ...
  reg_type_en: string;            // "Off-Plan Properties" | "Existing Properties"
  property_type_en: string;       // "Unit" | "Villa" | "Land" ...
  property_sub_type_en: string;   // "Flat" | "Villa" ...
  area_name_en: string;
  building_name_en: string;
  project_name_en: string;
  master_project_en: string;
  rooms_en: string;               // "1 B/R" | "Studio" ...
  procedure_area: number;         // sq.m.
  actual_worth: number;           // AED transaction price
  meter_sale_price: number;       // AED per sq.m.
}

/** Map DLD rooms_en ("1 B/R", "Studio", "PENTHOUSE") → our UnitSize bucket. */
export function dldRoomsBucket(roomsEn: string): string | null {
  const r = String(roomsEn ?? "").toLowerCase();
  if (r.includes("studio")) return "STU";
  const m = r.match(/(\d+)\s*b\/?r/);
  if (!m) return null;
  const beds = parseInt(m[1], 10);
  if (beds <= 1) return "1BR";
  if (beds === 2) return "2BR";
  if (beds === 3) return "3BR";
  return beds + "BR";
}

export interface SaleStat {
  medianPrice: number;
  p25Price: number;
  p75Price: number;
  medianAedPerSqft: number;
  medianSqft: number;
  offPlanShare: number;   // 0–1, fraction of sample that was off-plan
  n: number;
  asOf: string;            // "YYYY-MM" of most recent transaction
  source: "dda-live";
}

/** Compute sale-price stats from an array of transaction records. */
export function computeSaleStats(transactions: DLDSaleTransaction[]): SaleStat | null {
  const clean = transactions.filter(
    t => t.actual_worth > 50_000 && t.actual_worth < 500_000_000 && t.procedure_area > 5 && t.procedure_area < 5_000
  );
  if (clean.length < 3) return null;

  const prices = clean.map(t => t.actual_worth).sort((a, b) => a - b);
  const perSqft = clean
    .map(t => Math.round(t.actual_worth / (t.procedure_area * 10.764)))
    .sort((a, b) => a - b);
  const sqftVals = clean.map(t => Math.round(t.procedure_area * 10.764)).sort((a, b) => a - b);
  const offPlanCount = clean.filter(t => t.reg_type_en === "Off-Plan Properties").length;
  const latestDate = clean.map(t => t.instance_date).filter(Boolean).sort().at(-1)?.slice(0, 7) ?? "";

  return {
    medianPrice: median(prices),
    p25Price: percentile(prices, 25),
    p75Price: percentile(prices, 75),
    medianAedPerSqft: median(perSqft),
    medianSqft: median(sqftVals),
    offPlanShare: Math.round((offPlanCount / clean.length) * 100) / 100,
    n: clean.length,
    asOf: latestDate,
    source: "dda-live",
  };
}

/** Fetch sale transactions for a project name, filtered to a date window. */
export async function fetchSaleTransactions(
  projectName: string,
  options: { daysBack?: number; maxRecords?: number } = {}
): Promise<DLDSaleTransaction[]> {
  const { daysBack = 365, maxRecords = 2000 } = options;

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysBack);
  const cutoffStr = cutoff.toISOString().slice(0, 10);

  const columns: (keyof DLDSaleTransaction)[] = [
    "transaction_id", "instance_date", "trans_group_en", "procedure_name_en", "reg_type_en",
    "property_type_en", "property_sub_type_en", "area_name_en", "building_name_en",
    "project_name_en", "master_project_en", "rooms_en", "procedure_area", "actual_worth",
    "meter_sale_price",
  ];

  async function fetchForName(
    field: "project_name_en" | "building_name_en", dldName: string, exact: boolean
  ): Promise<DLDSaleTransaction[]> {
    const all: DLDSaleTransaction[] = [];
    let page = 1;
    const pageSize = 1000;
    while (all.length < maxRecords) {
      const { results } = await ddaQuery<DLDSaleTransaction>({
        entity: "dld",
        dataset: "dld_transactions-open-api",
        page,
        pageSize,
        columns: columns as string[],
        filters: { trans_group_en: "Sales" },
        ...(exact
          ? { likeFilters: { [field]: dldName } }
          : { likeFilters: { [field]: `${dldName}%` } }
        ),
        orderBy: "instance_date",
        orderDir: "desc",
      });
      if (!results.length) break;
      const recent = results.filter(t => t.instance_date >= cutoffStr && t.property_type_en === "Unit");
      all.push(...recent);
      if (results.length < pageSize) break;
      page++;
    }
    return all;
  }

  const canonicalName = resolveDLDName(projectName);
  if (canonicalName) {
    const rows = await fetchForName("project_name_en", canonicalName, true);
    if (rows.length > 0) return rows;
  }

  const variants = buildDLDVariants(projectName);
  for (const variant of variants) {
    if (canonicalName && variant.toUpperCase() === canonicalName.toUpperCase()) continue;
    const rows = await fetchForName("project_name_en", variant, false);
    if (rows.length > 0) return rows;
  }

  // Fallback: some DLD records (especially individual towers within a larger
  // complex) store the name under building_name_en rather than project_name_en.
  for (const variant of variants) {
    const rows = await fetchForName("building_name_en", variant, false);
    if (rows.length > 0) return rows;
  }

  return [];
}

// ── DLD valuations (dld_valuation-open-api) ─────────────────────────────────
// Note: this dataset only exposes area_name_en (no building/project name), so
// results are keyed by area rather than by building.

export interface DLDValuation {
  procedure_id: number;
  procedure_year: number;
  instance_date: string;         // "YYYY-MM-DD HH:mm:ss"
  actual_worth: number;
  row_status_code: string;       // "COMPLETED" ...
  procedure_area: number;        // sq.m.
  property_type_en: string;
  property_sub_type_en: string;
  area_name_en: string;
  actual_area: number;           // sq.m.
  property_total_value: number;
}

export interface ValuationStat {
  medianValue: number;
  medianAedPerSqft: number;
  n: number;
  asOf: string;
  source: "dda-live";
}

export function computeValuationStats(valuations: DLDValuation[]): ValuationStat | null {
  const clean = valuations.filter(
    v => v.row_status_code === "COMPLETED" && v.actual_worth > 50_000 && v.actual_area > 5 && v.actual_area < 5_000
  );
  if (clean.length < 3) return null;

  const values = clean.map(v => v.actual_worth).sort((a, b) => a - b);
  const perSqft = clean
    .map(v => Math.round(v.actual_worth / (v.actual_area * 10.764)))
    .sort((a, b) => a - b);
  const latestDate = clean.map(v => v.instance_date).filter(Boolean).sort().at(-1)?.slice(0, 7) ?? "";

  return {
    medianValue: median(values),
    medianAedPerSqft: median(perSqft),
    n: clean.length,
    asOf: latestDate,
    source: "dda-live",
  };
}

/** Fetch completed property valuations for an area name, filtered to a date window. */
export async function fetchAreaValuations(
  areaName: string,
  options: { daysBack?: number; maxRecords?: number } = {}
): Promise<DLDValuation[]> {
  const { daysBack = 730, maxRecords = 2000 } = options;

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - daysBack);
  const cutoffStr = cutoff.toISOString().slice(0, 10);

  const columns: (keyof DLDValuation)[] = [
    "procedure_id", "procedure_year", "instance_date", "actual_worth", "row_status_code",
    "procedure_area", "property_type_en", "property_sub_type_en", "area_name_en",
    "actual_area", "property_total_value",
  ];

  const all: DLDValuation[] = [];
  let page = 1;
  const pageSize = 1000;
  while (all.length < maxRecords) {
    const { results } = await ddaQuery<DLDValuation>({
      entity: "dld",
      dataset: "dld_valuation-open-api",
      page,
      pageSize,
      columns: columns as string[],
      likeFilters: { area_name_en: `${areaName}%` },
      orderBy: "instance_date",
      orderDir: "desc",
    });
    if (!results.length) break;
    const recent = results.filter(v => v.instance_date >= cutoffStr);
    all.push(...recent);
    if (results.length < pageSize) break;
    page++;
  }
  return all;
}
