export const DET_FULL_INVENTORY: Record<string, Array<{ cat: string; item: string; spec: string; qty: number; unitPrice: number }>> = {
  "Studio": [
    { cat: "Compliance & Safety", item: "SIRA-Approved Smart Lock", spec: "Connected to Keyless/DET portal system", qty: 1, unitPrice: 800 },
    { cat: "Compliance & Safety", item: "Fire Extinguisher (4.5kg Powder)", spec: "Certified, tag valid for 1 year, kitchen area", qty: 1, unitPrice: 150 },
    { cat: "Compliance & Safety", item: "Fire Blanket", spec: "Quick-release fiberglass blanket for kitchen", qty: 1, unitPrice: 45 },
    { cat: "Compliance & Safety", item: "First Aid Kit", spec: "Fully stocked as per Dubai Health Authority standards", qty: 1, unitPrice: 65 },
    { cat: "Compliance & Safety", item: "DET QR Code & Evacuation Plan Framed", spec: "Mounted below DEWA plaque / inside door", qty: 1, unitPrice: 50 },
    { cat: "Compliance & Safety", item: "Digital Safe Box", spec: "Electronic lock, anchored inside wardrobe", qty: 1, unitPrice: 180 },
    { cat: "Compliance & Safety", item: "Smoke Detectors (Standalone / Interlinked)", spec: "Battery backup (if not building central)", qty: 2, unitPrice: 80 },
    { cat: "Living & Dining", item: "Sofa / Sofa Bed", spec: "3-seater durable upholstery (L-shape or standard)", qty: 1, unitPrice: 1800 },
    { cat: "Living & Dining", item: "Coffee Table", spec: "Tempered glass or solid laminate wood", qty: 1, unitPrice: 250 },
    { cat: "Living & Dining", item: "Smart TV (4K UHD)", spec: "50-inch to 65-inch with Netflix/YouTube access", qty: 1, unitPrice: 1200 },
    { cat: "Living & Dining", item: "TV Console Table", spec: "With cable management and storage slots", qty: 1, unitPrice: 350 },
    { cat: "Living & Dining", item: "Dining Table", spec: "Sized relative to maximum occupancy capacity", qty: 1, unitPrice: 600 },
    { cat: "Living & Dining", item: "Dining Chairs", spec: "Padded comfortable chairs with high backrest", qty: 2, unitPrice: 150 },
    { cat: "Living & Dining", item: "High-Speed Wi-Fi Router / Mesh Node", spec: "Dual-band high throughput router setup", qty: 1, unitPrice: 300 },
    { cat: "Living & Dining", item: "Blackout Curtains / Blinds Set", spec: "Full length window coverage for living room", qty: 1, unitPrice: 400 },
    { cat: "Living & Dining", item: "Floor Lamp / Accent Lighting", spec: "Warm LED lighting for ambient hotel atmosphere", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "King/Queen Bed Frame", spec: "Solid build timber or upholstered headboard frame", qty: 1, unitPrice: 900 },
    { cat: "Bedroom Essentials", item: "Hotel Grade Orthopedic Mattress", spec: "Pocket spring medium-firm, minimum 20cm thickness", qty: 1, unitPrice: 1000 },
    { cat: "Bedroom Essentials", item: "Bedside Tables", spec: "Set of 2 units flanking the bed structure", qty: 1, unitPrice: 240 },
    { cat: "Bedroom Essentials", item: "Bedside Lamps with USB Ports", spec: "Set of 2 lamps with integrated guest charging points", qty: 1, unitPrice: 160 },
    { cat: "Bedroom Essentials", item: "Hotel Pillows (Pack of 4)", spec: "Hypoallergenic down-alternative, two firm, two soft", qty: 1, unitPrice: 120 },
    { cat: "Bedroom Essentials", item: "All-Season Duvet & Protector", spec: "Microfiber filling with waterproof quilted mattress cover", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "Premium White Linen Set (2 Full Changes)", spec: "200+ Thread Count: 2x Fitted sheets, 2x Duvet covers, 8x Pillowcases", qty: 1, unitPrice: 350 },
    { cat: "Bedroom Essentials", item: "Wardrobe Hangers Pack", spec: "Set of 20 high-quality wooden/rubberized anti-slip hangers", qty: 1, unitPrice: 40 },
    { cat: "Bedroom Essentials", item: "Full-Length Dresser Mirror", spec: "Wall-mounted or freestanding structural panel mirror", qty: 1, unitPrice: 150 },
    { cat: "Bedroom Essentials", item: "Bedroom Blackout Curtains Set", spec: "Strict thermal/light blockage for guest sleep comfort", qty: 1, unitPrice: 350 },
    { cat: "Kitchen & Appliances", item: "Refrigerator & Freezer Combo", spec: "No-frost, minimum 300L energy efficient double door", qty: 1, unitPrice: 1400 },
    { cat: "Kitchen & Appliances", item: "Gas/Electric Cooker & Oven", spec: "4-burner integrated unit with safety gas-cutoff mechanism", qty: 1, unitPrice: 1200 },
    { cat: "Kitchen & Appliances", item: "Microwave Oven", spec: "Digital control interface, 20L minimum volume capacity", qty: 1, unitPrice: 250 },
    { cat: "Kitchen & Appliances", item: "Electric Water Kettle", spec: "Stainless steel automatic auto-shutoff 1.7L boiler", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "2-Slot Bread Toaster", spec: "Variable browning control settings interface", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Nespresso Capsule Coffee Machine", spec: "Espresso pod maker for premium welcome tier rating", qty: 1, unitPrice: 450 },
    { cat: "Kitchen & Appliances", item: "Washing Machine & Dryer Combo", spec: "Front load 7kg/5kg wash-and-dry automated cycles", qty: 1, unitPrice: 1600 },
    { cat: "Kitchen & Appliances", item: "Non-Stick Cookware Set", spec: "2 Frying pans, 2 Casserole pots with glass lids, 1 wok", qty: 1, unitPrice: 280 },
    { cat: "Kitchen & Appliances", item: "Chef Knife & Cutting Board Set", spec: "Stainless steel knife bundle + multi-color hygienic boards", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Dinnerware Sets (Plates & Bowls)", spec: "Corelle or ceramic chip-resistant sets (scaled to max capacity)", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Glassware Set (Water & Wine)", spec: "High transparency tempered lead-free glassware items", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "Stainless Steel Cutlery Set", spec: "Forks, knives, tablespoons, teaspoons boxed package", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Kitchen Trash Can & Tool Set", spec: "Step-on airtight pedal bin, can opener, ladles, corkscrew", qty: 1, unitPrice: 140 },
    { cat: "Bathroom Amenities", item: "Premium Towels Set (2 Changes)", spec: "100% Cotton 600GSM: Bath, Hand, Face towels per occupant", qty: 2, unitPrice: 90 },
    { cat: "Bathroom Amenities", item: "Ionic Hairdryer", spec: "Wall-mount or storage bracket type 1800W+ capacity", qty: 1, unitPrice: 110 },
    { cat: "Bathroom Amenities", item: "Pedal Waste Bin & Toilet Brush Set", spec: "Stainless steel rust-free bathroom functional accessory", qty: 1, unitPrice: 70 },
    { cat: "Bathroom Amenities", item: "Non-Slip Shower Mat & Floor Towel", spec: "Rubberized anti-skid backing for liability compliance", qty: 1, unitPrice: 50 },
    { cat: "Utilities & Upkeep", item: "Vacuum Cleaner (Bagless)", spec: "High suction multi-surface cyclical motor assembly", qty: 1, unitPrice: 350 },
    { cat: "Utilities & Upkeep", item: "Ironing Board & Steam Iron Set", spec: "Foldable padded heavy duty board + vertical steam generator", qty: 1, unitPrice: 220 },
    { cat: "Utilities & Upkeep", item: "Cloth Drying Rack", spec: "Collapsible wing rack for balcony layout setting", qty: 1, unitPrice: 95 },
    { cat: "Utilities & Upkeep", item: "Mop, Broom & Cleaning Supply Bundle", spec: "Microfiber floor mop, soft bristles, starter cleaning fluids", qty: 1, unitPrice: 110 },
    { cat: "Utilities & Upkeep", item: "Islamic Prayer Mat", spec: "Standard clean textile layout (Required by DET checklist regulations)", qty: 1, unitPrice: 35 },
  ],
  "1BR": [
    { cat: "Compliance & Safety", item: "SIRA-Approved Smart Lock", spec: "Connected to Keyless/DET portal system", qty: 1, unitPrice: 800 },
    { cat: "Compliance & Safety", item: "Fire Extinguisher (4.5kg Powder)", spec: "Certified, tag valid for 1 year, kitchen area", qty: 1, unitPrice: 150 },
    { cat: "Compliance & Safety", item: "Fire Blanket", spec: "Quick-release fiberglass blanket for kitchen", qty: 1, unitPrice: 45 },
    { cat: "Compliance & Safety", item: "First Aid Kit", spec: "Fully stocked as per Dubai Health Authority standards", qty: 1, unitPrice: 65 },
    { cat: "Compliance & Safety", item: "DET QR Code & Evacuation Plan Framed", spec: "Mounted below DEWA plaque / inside door", qty: 1, unitPrice: 50 },
    { cat: "Compliance & Safety", item: "Digital Safe Box", spec: "Electronic lock, anchored inside wardrobe", qty: 1, unitPrice: 180 },
    { cat: "Compliance & Safety", item: "Smoke Detectors (Standalone / Interlinked)", spec: "Battery backup (if not building central)", qty: 2, unitPrice: 80 },
    { cat: "Living & Dining", item: "Sofa / Sofa Bed", spec: "3-seater durable upholstery (L-shape or standard)", qty: 1, unitPrice: 1800 },
    { cat: "Living & Dining", item: "Coffee Table", spec: "Tempered glass or solid laminate wood", qty: 1, unitPrice: 250 },
    { cat: "Living & Dining", item: "Smart TV (4K UHD)", spec: "50-inch to 65-inch with Netflix/YouTube access", qty: 1, unitPrice: 1200 },
    { cat: "Living & Dining", item: "TV Console Table", spec: "With cable management and storage slots", qty: 1, unitPrice: 350 },
    { cat: "Living & Dining", item: "Dining Table", spec: "Sized relative to maximum occupancy capacity", qty: 1, unitPrice: 600 },
    { cat: "Living & Dining", item: "Dining Chairs", spec: "Padded comfortable chairs with high backrest — 2–4 depending on space", qty: 2, unitPrice: 150 },
    { cat: "Living & Dining", item: "High-Speed Wi-Fi Router / Mesh Node", spec: "Dual-band high throughput router setup", qty: 1, unitPrice: 300 },
    { cat: "Living & Dining", item: "Blackout Curtains / Blinds Set", spec: "Full length window coverage for living room", qty: 1, unitPrice: 400 },
    { cat: "Living & Dining", item: "Floor Lamp / Accent Lighting", spec: "Warm LED lighting for ambient hotel atmosphere", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "King/Queen Bed Frame", spec: "Solid build timber or upholstered headboard frame", qty: 1, unitPrice: 900 },
    { cat: "Bedroom Essentials", item: "Hotel Grade Orthopedic Mattress", spec: "Pocket spring medium-firm, minimum 20cm thickness", qty: 1, unitPrice: 1000 },
    { cat: "Bedroom Essentials", item: "Bedside Tables", spec: "Set of 2 units flanking the bed structure", qty: 1, unitPrice: 240 },
    { cat: "Bedroom Essentials", item: "Bedside Lamps with USB Ports", spec: "Set of 2 lamps with integrated guest charging points", qty: 1, unitPrice: 160 },
    { cat: "Bedroom Essentials", item: "Hotel Pillows (Pack of 4)", spec: "Hypoallergenic down-alternative, two firm, two soft", qty: 1, unitPrice: 120 },
    { cat: "Bedroom Essentials", item: "All-Season Duvet & Protector", spec: "Microfiber filling with waterproof quilted mattress cover", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "Premium White Linen Set (2 Full Changes)", spec: "200+ Thread Count: 2x Fitted sheets, 2x Duvet covers, 8x Pillowcases", qty: 1, unitPrice: 350 },
    { cat: "Bedroom Essentials", item: "Wardrobe Hangers Pack", spec: "Set of 20 high-quality wooden/rubberized anti-slip hangers", qty: 1, unitPrice: 40 },
    { cat: "Bedroom Essentials", item: "Full-Length Dresser Mirror", spec: "Wall-mounted or freestanding structural panel mirror", qty: 1, unitPrice: 150 },
    { cat: "Bedroom Essentials", item: "Bedroom Blackout Curtains Set", spec: "Strict thermal/light blockage for guest sleep comfort", qty: 1, unitPrice: 350 },
    { cat: "Kitchen & Appliances", item: "Refrigerator & Freezer Combo", spec: "No-frost, minimum 300L energy efficient double door", qty: 1, unitPrice: 1400 },
    { cat: "Kitchen & Appliances", item: "Gas/Electric Cooker & Oven", spec: "4-burner integrated unit with safety gas-cutoff mechanism", qty: 1, unitPrice: 1200 },
    { cat: "Kitchen & Appliances", item: "Microwave Oven", spec: "Digital control interface, 20L minimum volume capacity", qty: 1, unitPrice: 250 },
    { cat: "Kitchen & Appliances", item: "Electric Water Kettle", spec: "Stainless steel automatic auto-shutoff 1.7L boiler", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "2-Slot Bread Toaster", spec: "Variable browning control settings interface", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Nespresso Capsule Coffee Machine", spec: "Espresso pod maker for premium welcome tier rating", qty: 1, unitPrice: 450 },
    { cat: "Kitchen & Appliances", item: "Washing Machine & Dryer Combo", spec: "Front load 7kg/5kg wash-and-dry automated cycles", qty: 1, unitPrice: 1600 },
    { cat: "Kitchen & Appliances", item: "Non-Stick Cookware Set", spec: "2 Frying pans, 2 Casserole pots with glass lids, 1 wok", qty: 1, unitPrice: 280 },
    { cat: "Kitchen & Appliances", item: "Chef Knife & Cutting Board Set", spec: "Stainless steel knife bundle + multi-color hygienic boards", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Dinnerware Sets (Plates & Bowls)", spec: "Corelle or ceramic chip-resistant sets (scaled to max capacity)", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Glassware Set (Water & Wine)", spec: "High transparency tempered lead-free glassware items", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "Stainless Steel Cutlery Set", spec: "Forks, knives, tablespoons, teaspoons boxed package", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Kitchen Trash Can & Tool Set", spec: "Step-on airtight pedal bin, can opener, ladles, corkscrew", qty: 1, unitPrice: 140 },
    { cat: "Bathroom Amenities", item: "Premium Towels Set (2 Changes)", spec: "100% Cotton 600GSM: Bath, Hand, Face towels per occupant", qty: 2, unitPrice: 90 },
    { cat: "Bathroom Amenities", item: "Ionic Hairdryer", spec: "Wall-mount or storage bracket type 1800W+ capacity", qty: 1, unitPrice: 110 },
    { cat: "Bathroom Amenities", item: "Pedal Waste Bin & Toilet Brush Set", spec: "Stainless steel rust-free bathroom functional accessory", qty: 2, unitPrice: 70 },
    { cat: "Bathroom Amenities", item: "Non-Slip Shower Mat & Floor Towel", spec: "Rubberized anti-skid backing for liability compliance", qty: 2, unitPrice: 50 },
    { cat: "Utilities & Upkeep", item: "Vacuum Cleaner (Bagless)", spec: "High suction multi-surface cyclical motor assembly", qty: 1, unitPrice: 350 },
    { cat: "Utilities & Upkeep", item: "Ironing Board & Steam Iron Set", spec: "Foldable padded heavy duty board + vertical steam generator", qty: 1, unitPrice: 220 },
    { cat: "Utilities & Upkeep", item: "Cloth Drying Rack", spec: "Collapsible wing rack for balcony layout setting", qty: 1, unitPrice: 95 },
    { cat: "Utilities & Upkeep", item: "Mop, Broom & Cleaning Supply Bundle", spec: "Microfiber floor mop, soft bristles, starter cleaning fluids", qty: 1, unitPrice: 110 },
    { cat: "Utilities & Upkeep", item: "Islamic Prayer Mat", spec: "Standard clean textile layout (Required by DET checklist regulations)", qty: 1, unitPrice: 35 },
  ],
  "2BR": [
    { cat: "Compliance & Safety", item: "SIRA-Approved Smart Lock", spec: "Connected to Keyless/DET portal system", qty: 1, unitPrice: 800 },
    { cat: "Compliance & Safety", item: "Fire Extinguisher (4.5kg Powder)", spec: "Certified, tag valid for 1 year, kitchen area", qty: 1, unitPrice: 150 },
    { cat: "Compliance & Safety", item: "Fire Blanket", spec: "Quick-release fiberglass blanket for kitchen", qty: 1, unitPrice: 45 },
    { cat: "Compliance & Safety", item: "First Aid Kit", spec: "Fully stocked as per Dubai Health Authority standards", qty: 1, unitPrice: 65 },
    { cat: "Compliance & Safety", item: "DET QR Code & Evacuation Plan Framed", spec: "Mounted below DEWA plaque / inside door", qty: 1, unitPrice: 50 },
    { cat: "Compliance & Safety", item: "Digital Safe Box", spec: "Electronic lock, anchored inside wardrobe", qty: 2, unitPrice: 180 },
    { cat: "Compliance & Safety", item: "Smoke Detectors (Standalone / Interlinked)", spec: "Battery backup (if not building central)", qty: 3, unitPrice: 80 },
    { cat: "Living & Dining", item: "Sofa / Sofa Bed", spec: "3-seater durable upholstery (L-shape or standard)", qty: 1, unitPrice: 2340 },
    { cat: "Living & Dining", item: "Coffee Table", spec: "Tempered glass or solid laminate wood", qty: 1, unitPrice: 250 },
    { cat: "Living & Dining", item: "Smart TV (4K UHD)", spec: "50-inch to 65-inch with Netflix/YouTube access", qty: 1, unitPrice: 1560 },
    { cat: "Living & Dining", item: "TV Console Table", spec: "With cable management and storage slots", qty: 1, unitPrice: 350 },
    { cat: "Living & Dining", item: "Dining Table", spec: "Sized relative to maximum occupancy capacity", qty: 1, unitPrice: 780 },
    { cat: "Living & Dining", item: "Dining Chairs", spec: "Padded comfortable chairs with high backrest", qty: 6, unitPrice: 150 },
    { cat: "Living & Dining", item: "High-Speed Wi-Fi Router / Mesh Node", spec: "Dual-band high throughput router setup", qty: 1, unitPrice: 300 },
    { cat: "Living & Dining", item: "Blackout Curtains / Blinds Set", spec: "Full length window coverage for living room", qty: 1, unitPrice: 400 },
    { cat: "Living & Dining", item: "Floor Lamp / Accent Lighting", spec: "Warm LED lighting for ambient hotel atmosphere", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "King/Queen Bed Frame", spec: "Solid build timber or upholstered headboard frame", qty: 2, unitPrice: 900 },
    { cat: "Bedroom Essentials", item: "Hotel Grade Orthopedic Mattress", spec: "Pocket spring medium-firm, minimum 20cm thickness", qty: 2, unitPrice: 1000 },
    { cat: "Bedroom Essentials", item: "Bedside Tables", spec: "Set of 2 units flanking the bed structure", qty: 2, unitPrice: 240 },
    { cat: "Bedroom Essentials", item: "Bedside Lamps with USB Ports", spec: "Set of 2 lamps with integrated guest charging points", qty: 2, unitPrice: 160 },
    { cat: "Bedroom Essentials", item: "Hotel Pillows (Pack of 4)", spec: "Hypoallergenic down-alternative, two firm, two soft", qty: 2, unitPrice: 120 },
    { cat: "Bedroom Essentials", item: "All-Season Duvet & Protector", spec: "Microfiber filling with waterproof quilted mattress cover", qty: 2, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "Premium White Linen Set (2 Full Changes)", spec: "200+ Thread Count: 2x Fitted sheets, 2x Duvet covers, 8x Pillowcases", qty: 2, unitPrice: 350 },
    { cat: "Bedroom Essentials", item: "Wardrobe Hangers Pack", spec: "Set of 20 high-quality wooden/rubberized anti-slip hangers", qty: 2, unitPrice: 40 },
    { cat: "Bedroom Essentials", item: "Full-Length Dresser Mirror", spec: "Wall-mounted or freestanding structural panel mirror", qty: 2, unitPrice: 150 },
    { cat: "Bedroom Essentials", item: "Bedroom Blackout Curtains Set", spec: "Strict thermal/light blockage for guest sleep comfort", qty: 2, unitPrice: 350 },
    { cat: "Kitchen & Appliances", item: "Refrigerator & Freezer Combo", spec: "No-frost, minimum 300L energy efficient double door", qty: 1, unitPrice: 1400 },
    { cat: "Kitchen & Appliances", item: "Gas/Electric Cooker & Oven", spec: "4-burner integrated unit with safety gas-cutoff mechanism", qty: 1, unitPrice: 1200 },
    { cat: "Kitchen & Appliances", item: "Microwave Oven", spec: "Digital control interface, 20L minimum volume capacity", qty: 1, unitPrice: 250 },
    { cat: "Kitchen & Appliances", item: "Electric Water Kettle", spec: "Stainless steel automatic auto-shutoff 1.7L boiler", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "2-Slot Bread Toaster", spec: "Variable browning control settings interface", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Nespresso Capsule Coffee Machine", spec: "Espresso pod maker for premium welcome tier rating", qty: 1, unitPrice: 450 },
    { cat: "Kitchen & Appliances", item: "Washing Machine & Dryer Combo", spec: "Front load 7kg/5kg wash-and-dry automated cycles", qty: 1, unitPrice: 1600 },
    { cat: "Kitchen & Appliances", item: "Non-Stick Cookware Set", spec: "2 Frying pans, 2 Casserole pots with glass lids, 1 wok", qty: 1, unitPrice: 280 },
    { cat: "Kitchen & Appliances", item: "Chef Knife & Cutting Board Set", spec: "Stainless steel knife bundle + multi-color hygienic boards", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Dinnerware Sets (Plates & Bowls)", spec: "Corelle or ceramic chip-resistant sets (scaled to max capacity)", qty: 1, unitPrice: 180 },
    { cat: "Kitchen & Appliances", item: "Glassware Set (Water & Wine)", spec: "High transparency tempered lead-free glassware items", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Stainless Steel Cutlery Set", spec: "Forks, knives, tablespoons, teaspoons boxed package", qty: 1, unitPrice: 135 },
    { cat: "Kitchen & Appliances", item: "Kitchen Trash Can & Tool Set", spec: "Step-on airtight pedal bin, can opener, ladles, corkscrew", qty: 1, unitPrice: 140 },
    { cat: "Bathroom Amenities", item: "Premium Towels Set (2 Changes)", spec: "100% Cotton 600GSM: Bath, Hand, Face towels per occupant", qty: 4, unitPrice: 90 },
    { cat: "Bathroom Amenities", item: "Ionic Hairdryer", spec: "Wall-mount or storage bracket type 1800W+ capacity", qty: 1, unitPrice: 110 },
    { cat: "Bathroom Amenities", item: "Pedal Waste Bin & Toilet Brush Set", spec: "Stainless steel rust-free bathroom functional accessory", qty: 3, unitPrice: 70 },
    { cat: "Bathroom Amenities", item: "Non-Slip Shower Mat & Floor Towel", spec: "Rubberized anti-skid backing for liability compliance", qty: 3, unitPrice: 50 },
    { cat: "Utilities & Upkeep", item: "Vacuum Cleaner (Bagless)", spec: "High suction multi-surface cyclical motor assembly", qty: 1, unitPrice: 350 },
    { cat: "Utilities & Upkeep", item: "Ironing Board & Steam Iron Set", spec: "Foldable padded heavy duty board + vertical steam generator", qty: 1, unitPrice: 220 },
    { cat: "Utilities & Upkeep", item: "Cloth Drying Rack", spec: "Collapsible wing rack for balcony layout setting", qty: 1, unitPrice: 95 },
    { cat: "Utilities & Upkeep", item: "Mop, Broom & Cleaning Supply Bundle", spec: "Microfiber floor mop, soft bristles, starter cleaning fluids", qty: 1, unitPrice: 110 },
    { cat: "Utilities & Upkeep", item: "Islamic Prayer Mat", spec: "Standard clean textile layout (Required by DET checklist regulations)", qty: 2, unitPrice: 35 },
  ],
  "3BR": [
    { cat: "Compliance & Safety", item: "SIRA-Approved Smart Lock", spec: "Connected to Keyless/DET portal system", qty: 1, unitPrice: 800 },
    { cat: "Compliance & Safety", item: "Fire Extinguisher (4.5kg Powder)", spec: "Certified, tag valid for 1 year, kitchen area", qty: 1, unitPrice: 150 },
    { cat: "Compliance & Safety", item: "Fire Blanket", spec: "Quick-release fiberglass blanket for kitchen", qty: 1, unitPrice: 45 },
    { cat: "Compliance & Safety", item: "First Aid Kit", spec: "Fully stocked as per Dubai Health Authority standards", qty: 1, unitPrice: 65 },
    { cat: "Compliance & Safety", item: "DET QR Code & Evacuation Plan Framed", spec: "Mounted below DEWA plaque / inside door", qty: 1, unitPrice: 50 },
    { cat: "Compliance & Safety", item: "Digital Safe Box", spec: "Electronic lock, anchored inside wardrobe", qty: 3, unitPrice: 180 },
    { cat: "Compliance & Safety", item: "Smoke Detectors (Standalone / Interlinked)", spec: "Battery backup (if not building central)", qty: 4, unitPrice: 80 },
    { cat: "Living & Dining", item: "Sofa / Sofa Bed", spec: "3-seater durable upholstery (L-shape or standard)", qty: 1, unitPrice: 2880 },
    { cat: "Living & Dining", item: "Coffee Table", spec: "Tempered glass or solid laminate wood", qty: 1, unitPrice: 250 },
    { cat: "Living & Dining", item: "Smart TV (4K UHD)", spec: "50-inch to 65-inch with Netflix/YouTube access", qty: 1, unitPrice: 1920 },
    { cat: "Living & Dining", item: "TV Console Table", spec: "With cable management and storage slots", qty: 1, unitPrice: 350 },
    { cat: "Living & Dining", item: "Dining Table", spec: "Sized relative to maximum occupancy capacity", qty: 1, unitPrice: 960 },
    { cat: "Living & Dining", item: "Dining Chairs", spec: "Padded comfortable chairs with high backrest", qty: 6, unitPrice: 150 },
    { cat: "Living & Dining", item: "High-Speed Wi-Fi Router / Mesh Node", spec: "Dual-band high throughput router setup", qty: 2, unitPrice: 300 },
    { cat: "Living & Dining", item: "Blackout Curtains / Blinds Set", spec: "Full length window coverage for living room", qty: 1, unitPrice: 400 },
    { cat: "Living & Dining", item: "Floor Lamp / Accent Lighting", spec: "Warm LED lighting for ambient hotel atmosphere", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "King/Queen Bed Frame", spec: "Solid build timber or upholstered headboard frame", qty: 3, unitPrice: 900 },
    { cat: "Bedroom Essentials", item: "Hotel Grade Orthopedic Mattress", spec: "Pocket spring medium-firm, minimum 20cm thickness", qty: 3, unitPrice: 1000 },
    { cat: "Bedroom Essentials", item: "Bedside Tables", spec: "Set of 2 units flanking the bed structure", qty: 3, unitPrice: 240 },
    { cat: "Bedroom Essentials", item: "Bedside Lamps with USB Ports", spec: "Set of 2 lamps with integrated guest charging points", qty: 3, unitPrice: 160 },
    { cat: "Bedroom Essentials", item: "Hotel Pillows (Pack of 4)", spec: "Hypoallergenic down-alternative, two firm, two soft", qty: 3, unitPrice: 120 },
    { cat: "Bedroom Essentials", item: "All-Season Duvet & Protector", spec: "Microfiber filling with waterproof quilted mattress cover", qty: 3, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "Premium White Linen Set (2 Full Changes)", spec: "200+ Thread Count: 2x Fitted sheets, 2x Duvet covers, 8x Pillowcases", qty: 3, unitPrice: 350 },
    { cat: "Bedroom Essentials", item: "Wardrobe Hangers Pack", spec: "Set of 20 high-quality wooden/rubberized anti-slip hangers", qty: 3, unitPrice: 40 },
    { cat: "Bedroom Essentials", item: "Full-Length Dresser Mirror", spec: "Wall-mounted or freestanding structural panel mirror", qty: 3, unitPrice: 150 },
    { cat: "Bedroom Essentials", item: "Bedroom Blackout Curtains Set", spec: "Strict thermal/light blockage for guest sleep comfort", qty: 3, unitPrice: 350 },
    { cat: "Kitchen & Appliances", item: "Refrigerator & Freezer Combo", spec: "No-frost, minimum 300L energy efficient double door", qty: 1, unitPrice: 1400 },
    { cat: "Kitchen & Appliances", item: "Gas/Electric Cooker & Oven", spec: "4-burner integrated unit with safety gas-cutoff mechanism", qty: 1, unitPrice: 1200 },
    { cat: "Kitchen & Appliances", item: "Microwave Oven", spec: "Digital control interface, 20L minimum volume capacity", qty: 1, unitPrice: 250 },
    { cat: "Kitchen & Appliances", item: "Electric Water Kettle", spec: "Stainless steel automatic auto-shutoff 1.7L boiler", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "2-Slot Bread Toaster", spec: "Variable browning control settings interface", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Nespresso Capsule Coffee Machine", spec: "Espresso pod maker for premium welcome tier rating", qty: 1, unitPrice: 450 },
    { cat: "Kitchen & Appliances", item: "Washing Machine & Dryer Combo", spec: "Front load 7kg/5kg wash-and-dry automated cycles", qty: 1, unitPrice: 1600 },
    { cat: "Kitchen & Appliances", item: "Non-Stick Cookware Set", spec: "2 Frying pans, 2 Casserole pots with glass lids, 1 wok", qty: 1, unitPrice: 280 },
    { cat: "Kitchen & Appliances", item: "Chef Knife & Cutting Board Set", spec: "Stainless steel knife bundle + multi-color hygienic boards", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Dinnerware Sets (Plates & Bowls)", spec: "Corelle or ceramic chip-resistant sets (scaled to max capacity)", qty: 1, unitPrice: 240 },
    { cat: "Kitchen & Appliances", item: "Glassware Set (Water & Wine)", spec: "High transparency tempered lead-free glassware items", qty: 1, unitPrice: 160 },
    { cat: "Kitchen & Appliances", item: "Stainless Steel Cutlery Set", spec: "Forks, knives, tablespoons, teaspoons boxed package", qty: 1, unitPrice: 180 },
    { cat: "Kitchen & Appliances", item: "Kitchen Trash Can & Tool Set", spec: "Step-on airtight pedal bin, can opener, ladles, corkscrew", qty: 1, unitPrice: 140 },
    { cat: "Bathroom Amenities", item: "Premium Towels Set (2 Changes)", spec: "100% Cotton 600GSM: Bath, Hand, Face towels per occupant", qty: 6, unitPrice: 90 },
    { cat: "Bathroom Amenities", item: "Ionic Hairdryer", spec: "Wall-mount or storage bracket type 1800W+ capacity", qty: 2, unitPrice: 110 },
    { cat: "Bathroom Amenities", item: "Pedal Waste Bin & Toilet Brush Set", spec: "Stainless steel rust-free bathroom functional accessory", qty: 4, unitPrice: 70 },
    { cat: "Bathroom Amenities", item: "Non-Slip Shower Mat & Floor Towel", spec: "Rubberized anti-skid backing for liability compliance", qty: 4, unitPrice: 50 },
    { cat: "Utilities & Upkeep", item: "Vacuum Cleaner (Bagless)", spec: "High suction multi-surface cyclical motor assembly", qty: 1, unitPrice: 350 },
    { cat: "Utilities & Upkeep", item: "Ironing Board & Steam Iron Set", spec: "Foldable padded heavy duty board + vertical steam generator", qty: 1, unitPrice: 220 },
    { cat: "Utilities & Upkeep", item: "Cloth Drying Rack", spec: "Collapsible wing rack for balcony layout setting", qty: 1, unitPrice: 95 },
    { cat: "Utilities & Upkeep", item: "Mop, Broom & Cleaning Supply Bundle", spec: "Microfiber floor mop, soft bristles, starter cleaning fluids", qty: 1, unitPrice: 110 },
    { cat: "Utilities & Upkeep", item: "Islamic Prayer Mat", spec: "Standard clean textile layout (Required by DET checklist regulations)", qty: 3, unitPrice: 35 },
  ],
  "4BR": [
    { cat: "Compliance & Safety", item: "SIRA-Approved Smart Lock", spec: "Connected to Keyless/DET portal system", qty: 1, unitPrice: 800 },
    { cat: "Compliance & Safety", item: "Fire Extinguisher (4.5kg Powder)", spec: "Certified, tag valid for 1 year, kitchen area", qty: 1, unitPrice: 150 },
    { cat: "Compliance & Safety", item: "Fire Blanket", spec: "Quick-release fiberglass blanket for kitchen", qty: 1, unitPrice: 45 },
    { cat: "Compliance & Safety", item: "First Aid Kit", spec: "Fully stocked as per Dubai Health Authority standards", qty: 1, unitPrice: 65 },
    { cat: "Compliance & Safety", item: "DET QR Code & Evacuation Plan Framed", spec: "Mounted below DEWA plaque / inside door", qty: 1, unitPrice: 50 },
    { cat: "Compliance & Safety", item: "Digital Safe Box", spec: "Electronic lock, anchored inside wardrobe", qty: 4, unitPrice: 180 },
    { cat: "Compliance & Safety", item: "Smoke Detectors (Standalone / Interlinked)", spec: "Battery backup (if not building central)", qty: 5, unitPrice: 80 },
    { cat: "Living & Dining", item: "Sofa / Sofa Bed", spec: "3-seater durable upholstery (L-shape or standard)", qty: 1, unitPrice: 3600 },
    { cat: "Living & Dining", item: "Coffee Table", spec: "Tempered glass or solid laminate wood", qty: 1, unitPrice: 250 },
    { cat: "Living & Dining", item: "Smart TV (4K UHD)", spec: "50-inch to 65-inch with Netflix/YouTube access", qty: 1, unitPrice: 2400 },
    { cat: "Living & Dining", item: "TV Console Table", spec: "With cable management and storage slots", qty: 1, unitPrice: 350 },
    { cat: "Living & Dining", item: "Dining Table", spec: "Sized relative to maximum occupancy capacity", qty: 1, unitPrice: 1200 },
    { cat: "Living & Dining", item: "Dining Chairs", spec: "Padded comfortable chairs with high backrest — 8–10 depending on space", qty: 8, unitPrice: 150 },
    { cat: "Living & Dining", item: "High-Speed Wi-Fi Router / Mesh Node", spec: "Dual-band high throughput router setup", qty: 2, unitPrice: 300 },
    { cat: "Living & Dining", item: "Blackout Curtains / Blinds Set", spec: "Full length window coverage for living room", qty: 1, unitPrice: 400 },
    { cat: "Living & Dining", item: "Floor Lamp / Accent Lighting", spec: "Warm LED lighting for ambient hotel atmosphere", qty: 1, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "King/Queen Bed Frame", spec: "Solid build timber or upholstered headboard frame", qty: 4, unitPrice: 900 },
    { cat: "Bedroom Essentials", item: "Hotel Grade Orthopedic Mattress", spec: "Pocket spring medium-firm, minimum 20cm thickness", qty: 4, unitPrice: 1000 },
    { cat: "Bedroom Essentials", item: "Bedside Tables", spec: "Set of 2 units flanking the bed structure", qty: 4, unitPrice: 240 },
    { cat: "Bedroom Essentials", item: "Bedside Lamps with USB Ports", spec: "Set of 2 lamps with integrated guest charging points", qty: 4, unitPrice: 160 },
    { cat: "Bedroom Essentials", item: "Hotel Pillows (Pack of 4)", spec: "Hypoallergenic down-alternative, two firm, two soft", qty: 4, unitPrice: 120 },
    { cat: "Bedroom Essentials", item: "All-Season Duvet & Protector", spec: "Microfiber filling with waterproof quilted mattress cover", qty: 4, unitPrice: 180 },
    { cat: "Bedroom Essentials", item: "Premium White Linen Set (2 Full Changes)", spec: "200+ Thread Count: 2x Fitted sheets, 2x Duvet covers, 8x Pillowcases", qty: 4, unitPrice: 350 },
    { cat: "Bedroom Essentials", item: "Wardrobe Hangers Pack", spec: "Set of 20 high-quality wooden/rubberized anti-slip hangers", qty: 4, unitPrice: 40 },
    { cat: "Bedroom Essentials", item: "Full-Length Dresser Mirror", spec: "Wall-mounted or freestanding structural panel mirror", qty: 4, unitPrice: 150 },
    { cat: "Bedroom Essentials", item: "Bedroom Blackout Curtains Set", spec: "Strict thermal/light blockage for guest sleep comfort", qty: 4, unitPrice: 350 },
    { cat: "Kitchen & Appliances", item: "Refrigerator & Freezer Combo", spec: "No-frost, minimum 300L energy efficient double door", qty: 1, unitPrice: 1400 },
    { cat: "Kitchen & Appliances", item: "Gas/Electric Cooker & Oven", spec: "4-burner integrated unit with safety gas-cutoff mechanism", qty: 1, unitPrice: 1200 },
    { cat: "Kitchen & Appliances", item: "Microwave Oven", spec: "Digital control interface, 20L minimum volume capacity", qty: 1, unitPrice: 250 },
    { cat: "Kitchen & Appliances", item: "Electric Water Kettle", spec: "Stainless steel automatic auto-shutoff 1.7L boiler", qty: 1, unitPrice: 80 },
    { cat: "Kitchen & Appliances", item: "2-Slot Bread Toaster", spec: "Variable browning control settings interface", qty: 1, unitPrice: 90 },
    { cat: "Kitchen & Appliances", item: "Nespresso Capsule Coffee Machine", spec: "Espresso pod maker for premium welcome tier rating", qty: 1, unitPrice: 450 },
    { cat: "Kitchen & Appliances", item: "Washing Machine & Dryer Combo", spec: "Front load 7kg/5kg wash-and-dry automated cycles", qty: 1, unitPrice: 1600 },
    { cat: "Kitchen & Appliances", item: "Non-Stick Cookware Set", spec: "2 Frying pans, 2 Casserole pots with glass lids, 1 wok", qty: 1, unitPrice: 280 },
    { cat: "Kitchen & Appliances", item: "Chef Knife & Cutting Board Set", spec: "Stainless steel knife bundle + multi-color hygienic boards", qty: 1, unitPrice: 120 },
    { cat: "Kitchen & Appliances", item: "Dinnerware Sets (Plates & Bowls)", spec: "Corelle or ceramic chip-resistant sets (scaled to max capacity)", qty: 1, unitPrice: 300 },
    { cat: "Kitchen & Appliances", item: "Glassware Set (Water & Wine)", spec: "High transparency tempered lead-free glassware items", qty: 1, unitPrice: 200 },
    { cat: "Kitchen & Appliances", item: "Stainless Steel Cutlery Set", spec: "Forks, knives, tablespoons, teaspoons boxed package", qty: 1, unitPrice: 225 },
    { cat: "Kitchen & Appliances", item: "Kitchen Trash Can & Tool Set", spec: "Step-on airtight pedal bin, can opener, ladles, corkscrew", qty: 1, unitPrice: 140 },
    { cat: "Bathroom Amenities", item: "Premium Towels Set (2 Changes)", spec: "100% Cotton 600GSM: Bath, Hand, Face towels per occupant", qty: 8, unitPrice: 90 },
    { cat: "Bathroom Amenities", item: "Ionic Hairdryer", spec: "Wall-mount or storage bracket type 1800W+ capacity", qty: 2, unitPrice: 110 },
    { cat: "Bathroom Amenities", item: "Pedal Waste Bin & Toilet Brush Set", spec: "Stainless steel rust-free bathroom functional accessory", qty: 5, unitPrice: 70 },
    { cat: "Bathroom Amenities", item: "Non-Slip Shower Mat & Floor Towel", spec: "Rubberized anti-skid backing for liability compliance", qty: 5, unitPrice: 50 },
    { cat: "Utilities & Upkeep", item: "Vacuum Cleaner (Bagless)", spec: "High suction multi-surface cyclical motor assembly", qty: 1, unitPrice: 350 },
    { cat: "Utilities & Upkeep", item: "Ironing Board & Steam Iron Set", spec: "Foldable padded heavy duty board + vertical steam generator", qty: 1, unitPrice: 220 },
    { cat: "Utilities & Upkeep", item: "Cloth Drying Rack", spec: "Collapsible wing rack for balcony layout setting", qty: 1, unitPrice: 95 },
    { cat: "Utilities & Upkeep", item: "Mop, Broom & Cleaning Supply Bundle", spec: "Microfiber floor mop, soft bristles, starter cleaning fluids", qty: 1, unitPrice: 110 },
    { cat: "Utilities & Upkeep", item: "Islamic Prayer Mat", spec: "Standard clean textile layout (Required by DET checklist regulations)", qty: 4, unitPrice: 35 },
  ],
};
