// Dubai STR management operators — Airbtics "Top Hosts in Dubai" export, 13 Aug 2026.
//
// Filtered to Airbtics-verified hosts with a published website and >=20 listings, i.e.
// management businesses rather than individual owners. 977 rows in, 167 retained.
// USD figures converted to AED at the pegged rate (3.6725); Airbtics reports in USD.
//
// Occupancy here is Airbtics' measure, validated against a known Dubai portfolio
// (Deluxe Holiday Homes ~78%). AirROI's equivalent understates by roughly 4x and is
// deliberately NOT used for this dataset.
//
// Ordered by portfolio revenue (listings x avg revenue). Sourced data only — AssetIntel
// adds no estimate here. Regenerate from a fresh Airbtics export rather than editing.

export interface DubaiOperator {
  name: string;
  website: string;
  listings: number;
  avgRating: number | null;
  avgOccupancy: number;
  avgRevenueAed: number | null;
  avgAdrAed: number | null;
  portfolioRevenueAed: number | null;
  inventoryGrowthPct: number | null;
  commonBedroom: string | null;
}

export const DUBAI_OPERATORS: DubaiOperator[] = [
  {
    "name": "Deluxe Holiday Homes",
    "website": "deluxehomes.com",
    "listings": 731,
    "avgRating": 4.2,
    "avgOccupancy": 0.78,
    "avgRevenueAed": 101053,
    "avgAdrAed": 749,
    "portfolioRevenueAed": 73869385,
    "inventoryGrowthPct": 40.04,
    "commonBedroom": "1"
  },
  {
    "name": "Vacationer",
    "website": "vacationerdubai.com",
    "listings": 363,
    "avgRating": 4.8,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 112110,
    "avgAdrAed": 911,
    "portfolioRevenueAed": 40696078,
    "inventoryGrowthPct": 46.37,
    "commonBedroom": "1"
  },
  {
    "name": "First Class Property Management",
    "website": "firstclass-dxb.com",
    "listings": 253,
    "avgRating": 4.9,
    "avgOccupancy": 0.86,
    "avgRevenueAed": 134131,
    "avgAdrAed": 808,
    "portfolioRevenueAed": 33935072,
    "inventoryGrowthPct": 118.1,
    "commonBedroom": "1"
  },
  {
    "name": "Mint Stay",
    "website": "themintstay.com",
    "listings": 171,
    "avgRating": 4.9,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 187342,
    "avgAdrAed": 1410,
    "portfolioRevenueAed": 32035408,
    "inventoryGrowthPct": 22.14,
    "commonBedroom": "2"
  },
  {
    "name": "Suiteable",
    "website": "suiteable.ae",
    "listings": 231,
    "avgRating": 4.7,
    "avgOccupancy": 0.72,
    "avgRevenueAed": 135460,
    "avgAdrAed": 1564,
    "portfolioRevenueAed": 31291298,
    "inventoryGrowthPct": 22.87,
    "commonBedroom": "1"
  },
  {
    "name": "LUX Holiday Home",
    "website": "https://www.luxholidayhome.com",
    "listings": 166,
    "avgRating": 4.8,
    "avgOccupancy": 0.75,
    "avgRevenueAed": 168902,
    "avgAdrAed": 995,
    "portfolioRevenueAed": 28037723,
    "inventoryGrowthPct": 32.8,
    "commonBedroom": "1"
  },
  {
    "name": "Blueground",
    "website": "https://www.theblueground.com",
    "listings": 548,
    "avgRating": 4.5,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 48668,
    "avgAdrAed": 951,
    "portfolioRevenueAed": 26670048,
    "inventoryGrowthPct": 53.93,
    "commonBedroom": "1"
  },
  {
    "name": "Westminster Holiday Homes and Resorts",
    "website": "westminsterholidays.com",
    "listings": 79,
    "avgRating": 4.5,
    "avgOccupancy": 0.57,
    "avgRevenueAed": 276649,
    "avgAdrAed": 1726,
    "portfolioRevenueAed": 21855305,
    "inventoryGrowthPct": 58.0,
    "commonBedroom": "1"
  },
  {
    "name": "Vogue Vacation Homes",
    "website": "voguevacationhomes.com",
    "listings": 152,
    "avgRating": 4.6,
    "avgOccupancy": 0.81,
    "avgRevenueAed": 128482,
    "avgAdrAed": 797,
    "portfolioRevenueAed": 19529327,
    "inventoryGrowthPct": 85.37,
    "commonBedroom": "1"
  },
  {
    "name": "Anna Apricus Holiday Homes",
    "website": "apricusholidayhomes.com",
    "listings": 136,
    "avgRating": 4.9,
    "avgOccupancy": 0.81,
    "avgRevenueAed": 141781,
    "avgAdrAed": 830,
    "portfolioRevenueAed": 19282153,
    "inventoryGrowthPct": 46.24,
    "commonBedroom": "1"
  },
  {
    "name": "Elite Royal Apartments",
    "website": "eliteroyalapartments.com",
    "listings": 60,
    "avgRating": 4.7,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 314399,
    "avgAdrAed": 1487,
    "portfolioRevenueAed": 18863943,
    "inventoryGrowthPct": 76.47,
    "commonBedroom": "3"
  },
  {
    "name": "Livbnb",
    "website": "livbnb.com",
    "listings": 156,
    "avgRating": 4.7,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 120260,
    "avgAdrAed": 1076,
    "portfolioRevenueAed": 18760511,
    "inventoryGrowthPct": 54.46,
    "commonBedroom": "1"
  },
  {
    "name": "LuxurybookingsFZE",
    "website": "luxurybookings.ae",
    "listings": 719,
    "avgRating": 4.7,
    "avgOccupancy": 0.23,
    "avgRevenueAed": 24584,
    "avgAdrAed": 668,
    "portfolioRevenueAed": 17675691,
    "inventoryGrowthPct": 50.42,
    "commonBedroom": "1"
  },
  {
    "name": "Alexander / GUESTA",
    "website": "guesta.ae",
    "listings": 129,
    "avgRating": 4.8,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 135277,
    "avgAdrAed": 705,
    "portfolioRevenueAed": 17450673,
    "inventoryGrowthPct": 25.24,
    "commonBedroom": "2"
  },
  {
    "name": "GOODSTAYDUBAICOM",
    "website": "goodstaydubai.com",
    "listings": 126,
    "avgRating": 5.0,
    "avgOccupancy": 0.9,
    "avgRevenueAed": 138259,
    "avgAdrAed": 716,
    "portfolioRevenueAed": 17420585,
    "inventoryGrowthPct": 36.96,
    "commonBedroom": "1"
  },
  {
    "name": "Airbetter",
    "website": "airbetter.com",
    "listings": 122,
    "avgRating": 4.0,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 135563,
    "avgAdrAed": 1050,
    "portfolioRevenueAed": 16538685,
    "inventoryGrowthPct": 54.43,
    "commonBedroom": "1"
  },
  {
    "name": "Berg Stays",
    "website": "bergstays.com",
    "listings": 55,
    "avgRating": 4.9,
    "avgOccupancy": 0.87,
    "avgRevenueAed": 288512,
    "avgAdrAed": 1362,
    "portfolioRevenueAed": 15868138,
    "inventoryGrowthPct": 41.03,
    "commonBedroom": "2"
  },
  {
    "name": "Like Home",
    "website": "likehome.ae",
    "listings": 107,
    "avgRating": 4.0,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 106914,
    "avgAdrAed": 1311,
    "portfolioRevenueAed": 11439779,
    "inventoryGrowthPct": 78.33,
    "commonBedroom": "2"
  },
  {
    "name": "\u2068365 Luxury Homes\u2069",
    "website": "365luxuryhomes.com",
    "listings": 24,
    "avgRating": 5.0,
    "avgOccupancy": 0.69,
    "avgRevenueAed": 451240,
    "avgAdrAed": 2769,
    "portfolioRevenueAed": 10829762,
    "inventoryGrowthPct": 60.0,
    "commonBedroom": "3"
  },
  {
    "name": "Frank Porter",
    "website": "https://www.frankporter.com",
    "listings": 88,
    "avgRating": 4.5,
    "avgOccupancy": 0.86,
    "avgRevenueAed": 122404,
    "avgAdrAed": 610,
    "portfolioRevenueAed": 10771589,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "1"
  },
  {
    "name": "Muhammad",
    "website": "exclusiveretreatsdubai.com",
    "listings": 143,
    "avgRating": 4.5,
    "avgOccupancy": 0.51,
    "avgRevenueAed": 72620,
    "avgAdrAed": 661,
    "portfolioRevenueAed": 10384662,
    "inventoryGrowthPct": 16.26,
    "commonBedroom": "1"
  },
  {
    "name": "Stella Stays",
    "website": "https://stellastays.com",
    "listings": 177,
    "avgRating": 4.7,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 58562,
    "avgAdrAed": 665,
    "portfolioRevenueAed": 10365418,
    "inventoryGrowthPct": 59.46,
    "commonBedroom": "1"
  },
  {
    "name": "Bnbme",
    "website": "bnbmehomes.com",
    "listings": 73,
    "avgRating": 4.7,
    "avgOccupancy": 0.64,
    "avgRevenueAed": 138288,
    "avgAdrAed": 1149,
    "portfolioRevenueAed": 10095023,
    "inventoryGrowthPct": 69.77,
    "commonBedroom": "2"
  },
  {
    "name": "Famco Vacation Homes Rental LLC",
    "website": "famliving.com",
    "listings": 110,
    "avgRating": 4.4,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 91570,
    "avgAdrAed": 918,
    "portfolioRevenueAed": 10072713,
    "inventoryGrowthPct": 161.9,
    "commonBedroom": "1"
  },
  {
    "name": "Aircay Holiday Homes",
    "website": "aircay.ae",
    "listings": 83,
    "avgRating": 4.7,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 120840,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 10029715,
    "inventoryGrowthPct": 38.33,
    "commonBedroom": "1"
  },
  {
    "name": "EDEN'S Homes & Villas",
    "website": "edenshomes.com",
    "listings": 37,
    "avgRating": 4.9,
    "avgOccupancy": 0.72,
    "avgRevenueAed": 268015,
    "avgAdrAed": 1318,
    "portfolioRevenueAed": 9916569,
    "inventoryGrowthPct": 37.04,
    "commonBedroom": "2"
  },
  {
    "name": "Trophy",
    "website": "trophystays.com",
    "listings": 133,
    "avgRating": 4.5,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 73009,
    "avgAdrAed": 690,
    "portfolioRevenueAed": 9710237,
    "inventoryGrowthPct": 90.0,
    "commonBedroom": "1"
  },
  {
    "name": "LUXFolio",
    "website": "luxfoliorealestate.ae/retreats",
    "listings": 104,
    "avgRating": 4.7,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 93076,
    "avgAdrAed": 727,
    "portfolioRevenueAed": 9679887,
    "inventoryGrowthPct": 82.46,
    "commonBedroom": "1"
  },
  {
    "name": "SmartStay",
    "website": "smartstay.me",
    "listings": 33,
    "avgRating": 5.0,
    "avgOccupancy": 0.77,
    "avgRevenueAed": 291567,
    "avgAdrAed": 1157,
    "portfolioRevenueAed": 9621715,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "2"
  },
  {
    "name": "The Prive Hospitality",
    "website": "theprive.ae",
    "listings": 104,
    "avgRating": 4.2,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 91434,
    "avgAdrAed": 959,
    "portfolioRevenueAed": 9509160,
    "inventoryGrowthPct": 48.57,
    "commonBedroom": "1"
  },
  {
    "name": "Luxury-Escapes",
    "website": "luxury-escapes.com",
    "listings": 75,
    "avgRating": 4.6,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 125967,
    "avgAdrAed": 635,
    "portfolioRevenueAed": 9447506,
    "inventoryGrowthPct": 22.95,
    "commonBedroom": "1"
  },
  {
    "name": "Medini Homes",
    "website": "medini-homes.com",
    "listings": 124,
    "avgRating": 4.7,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 75202,
    "avgAdrAed": 540,
    "portfolioRevenueAed": 9325021,
    "inventoryGrowthPct": 40.91,
    "commonBedroom": "0"
  },
  {
    "name": "NOX",
    "website": "noxdubai.com",
    "listings": 88,
    "avgRating": 4.6,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 99661,
    "avgAdrAed": 1091,
    "portfolioRevenueAed": 8770136,
    "inventoryGrowthPct": 83.33,
    "commonBedroom": "1"
  },
  {
    "name": "VayK Holiday Homes",
    "website": "vayk.ae",
    "listings": 122,
    "avgRating": 4.6,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 71213,
    "avgAdrAed": 720,
    "portfolioRevenueAed": 8688041,
    "inventoryGrowthPct": 67.12,
    "commonBedroom": "1"
  },
  {
    "name": "Daniels Holiday Homes",
    "website": "danielsholidayhomes.com",
    "listings": 54,
    "avgRating": 4.7,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 152302,
    "avgAdrAed": 1006,
    "portfolioRevenueAed": 8224321,
    "inventoryGrowthPct": 42.11,
    "commonBedroom": "1"
  },
  {
    "name": "Allsopp & Allsopp",
    "website": "allsoppandallsopp.com",
    "listings": 97,
    "avgRating": 4.7,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 84122,
    "avgAdrAed": 900,
    "portfolioRevenueAed": 8159862,
    "inventoryGrowthPct": 102.08,
    "commonBedroom": "1"
  },
  {
    "name": "OcleyHomes",
    "website": "ocleygroup.com",
    "listings": 108,
    "avgRating": 4.8,
    "avgOccupancy": 0.84,
    "avgRevenueAed": 73927,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 7984162,
    "inventoryGrowthPct": 63.64,
    "commonBedroom": "1"
  },
  {
    "name": "KeyRock Living",
    "website": "keyrockliving.com",
    "listings": 92,
    "avgRating": 4.7,
    "avgOccupancy": 0.81,
    "avgRevenueAed": 84816,
    "avgAdrAed": 734,
    "portfolioRevenueAed": 7803108,
    "inventoryGrowthPct": 206.67,
    "commonBedroom": "1"
  },
  {
    "name": "One and Half Dubai",
    "website": "oneandhalfdubai.com",
    "listings": 21,
    "avgRating": 4.8,
    "avgOccupancy": 0.66,
    "avgRevenueAed": 362171,
    "avgAdrAed": 2325,
    "portfolioRevenueAed": 7605590,
    "inventoryGrowthPct": 61.54,
    "commonBedroom": "5"
  },
  {
    "name": "SKYLINE SERENITY",
    "website": "skylineserenity.ae/book-your-stay",
    "listings": 22,
    "avgRating": 4.9,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 344433,
    "avgAdrAed": 1741,
    "portfolioRevenueAed": 7577521,
    "inventoryGrowthPct": 46.67,
    "commonBedroom": "2"
  },
  {
    "name": "HAPPY SEASON Holiday Homes",
    "website": "facebook.com/p/Happy-Season-Holiday-Homes-LLC-100083031026189",
    "listings": 73,
    "avgRating": 4.2,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 100638,
    "avgAdrAed": 727,
    "portfolioRevenueAed": 7346539,
    "inventoryGrowthPct": 65.91,
    "commonBedroom": "2"
  },
  {
    "name": "Carpe Diem Lifestyle",
    "website": "carpediemdxb.com",
    "listings": 69,
    "avgRating": 4.7,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 104835,
    "avgAdrAed": 808,
    "portfolioRevenueAed": 7233628,
    "inventoryGrowthPct": 30.19,
    "commonBedroom": "2"
  },
  {
    "name": "Luton Vacation Homes",
    "website": "https://luton.ae",
    "listings": 76,
    "avgRating": 4.5,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 91680,
    "avgAdrAed": 874,
    "portfolioRevenueAed": 6967702,
    "inventoryGrowthPct": 52.0,
    "commonBedroom": "1"
  },
  {
    "name": "The Costa Collection",
    "website": "thecostacollection.com",
    "listings": 72,
    "avgRating": 4.8,
    "avgOccupancy": 0.69,
    "avgRevenueAed": 94695,
    "avgAdrAed": 650,
    "portfolioRevenueAed": 6818070,
    "inventoryGrowthPct": 56.52,
    "commonBedroom": "2"
  },
  {
    "name": "Hive Holiday Homes",
    "website": "hiveservices.ae",
    "listings": 85,
    "avgRating": 4.4,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 79344,
    "avgAdrAed": 672,
    "portfolioRevenueAed": 6744271,
    "inventoryGrowthPct": 44.07,
    "commonBedroom": "1"
  },
  {
    "name": "HomesGetaway",
    "website": "homesgetaway.com",
    "listings": 54,
    "avgRating": 4.5,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 108383,
    "avgAdrAed": 701,
    "portfolioRevenueAed": 5852672,
    "inventoryGrowthPct": 20.0,
    "commonBedroom": "1"
  },
  {
    "name": "Czechin.ae",
    "website": "czechin.ae",
    "listings": 78,
    "avgRating": 4.9,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 72734,
    "avgAdrAed": 602,
    "portfolioRevenueAed": 5673241,
    "inventoryGrowthPct": 100.0,
    "commonBedroom": "1"
  },
  {
    "name": "MajeStay",
    "website": "majestay.com",
    "listings": 53,
    "avgRating": 5.0,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 105448,
    "avgAdrAed": 918,
    "portfolioRevenueAed": 5588770,
    "inventoryGrowthPct": 82.76,
    "commonBedroom": "1"
  },
  {
    "name": "Elegant Homes",
    "website": "eleganthomesuae.com",
    "listings": 29,
    "avgRating": 4.8,
    "avgOccupancy": 0.56,
    "avgRevenueAed": 192281,
    "avgAdrAed": 1583,
    "portfolioRevenueAed": 5576151,
    "inventoryGrowthPct": 81.25,
    "commonBedroom": "1"
  },
  {
    "name": "Locations",
    "website": "locations.ae",
    "listings": 67,
    "avgRating": 4.7,
    "avgOccupancy": 0.66,
    "avgRevenueAed": 82745,
    "avgAdrAed": 804,
    "portfolioRevenueAed": 5543922,
    "inventoryGrowthPct": 31.37,
    "commonBedroom": "1"
  },
  {
    "name": "Let2Rent",
    "website": "let2rent.com",
    "listings": 51,
    "avgRating": 4.7,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 107024,
    "avgAdrAed": 867,
    "portfolioRevenueAed": 5458224,
    "inventoryGrowthPct": 88.89,
    "commonBedroom": "1"
  },
  {
    "name": "Astatine Holiday Homes",
    "website": "astatineholiday.homes",
    "listings": 48,
    "avgRating": 4.6,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 112860,
    "avgAdrAed": 808,
    "portfolioRevenueAed": 5417261,
    "inventoryGrowthPct": 11.63,
    "commonBedroom": "1"
  },
  {
    "name": "TRPS Vacation Homes Rental LLC",
    "website": "trps.com",
    "listings": 71,
    "avgRating": 5.0,
    "avgOccupancy": 0.57,
    "avgRevenueAed": 74574,
    "avgAdrAed": 999,
    "portfolioRevenueAed": 5294739,
    "inventoryGrowthPct": 294.44,
    "commonBedroom": "1"
  },
  {
    "name": "Nasma Luxury Stays",
    "website": "nasmaluxurystays.com",
    "listings": 47,
    "avgRating": 4.4,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 112184,
    "avgAdrAed": 734,
    "portfolioRevenueAed": 5272641,
    "inventoryGrowthPct": 46.88,
    "commonBedroom": "1"
  },
  {
    "name": "Aurora Vacation Homes Rentals LLC",
    "website": "auroradxb.ae",
    "listings": 24,
    "avgRating": 5.0,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 217496,
    "avgAdrAed": 1102,
    "portfolioRevenueAed": 5219915,
    "inventoryGrowthPct": 50.0,
    "commonBedroom": "2"
  },
  {
    "name": "Stellium",
    "website": "stelliumhost.com",
    "listings": 39,
    "avgRating": 4.9,
    "avgOccupancy": 0.9,
    "avgRevenueAed": 133477,
    "avgAdrAed": 848,
    "portfolioRevenueAed": 5205603,
    "inventoryGrowthPct": 95.0,
    "commonBedroom": "1"
  },
  {
    "name": "Aparts.Ae",
    "website": "aparts.ae",
    "listings": 36,
    "avgRating": 4.9,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 142596,
    "avgAdrAed": 753,
    "portfolioRevenueAed": 5133450,
    "inventoryGrowthPct": 28.57,
    "commonBedroom": "1"
  },
  {
    "name": "Durrani Homes",
    "website": "durranihomes.com",
    "listings": 28,
    "avgRating": 4.4,
    "avgOccupancy": 0.53,
    "avgRevenueAed": 180390,
    "avgAdrAed": 1072,
    "portfolioRevenueAed": 5050907,
    "inventoryGrowthPct": 27.27,
    "commonBedroom": "1"
  },
  {
    "name": "Gardenia Holiday Homes ( Gardenia Suites )",
    "website": "gardeniaholidays.com",
    "listings": 39,
    "avgRating": 4.8,
    "avgOccupancy": 0.52,
    "avgRevenueAed": 126811,
    "avgAdrAed": 1183,
    "portfolioRevenueAed": 4945646,
    "inventoryGrowthPct": 105.26,
    "commonBedroom": "1"
  },
  {
    "name": "Waves Holiday Homes",
    "website": "wavesholidayhomes.com",
    "listings": 56,
    "avgRating": 4.7,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 87707,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 4911572,
    "inventoryGrowthPct": 75.0,
    "commonBedroom": "1"
  },
  {
    "name": "Welcome Home Apartments",
    "website": "welcomehome.ae",
    "listings": 53,
    "avgRating": 4.7,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 91030,
    "avgAdrAed": 856,
    "portfolioRevenueAed": 4824604,
    "inventoryGrowthPct": 76.67,
    "commonBedroom": "1"
  },
  {
    "name": "Allegiance Living",
    "website": "aliving.ae",
    "listings": 63,
    "avgRating": 4.6,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 74963,
    "avgAdrAed": 815,
    "portfolioRevenueAed": 4722673,
    "inventoryGrowthPct": 23.53,
    "commonBedroom": "1"
  },
  {
    "name": "Nexus Living",
    "website": "nexusliving.ae",
    "listings": 61,
    "avgRating": 4.9,
    "avgOccupancy": 0.79,
    "avgRevenueAed": 76638,
    "avgAdrAed": 742,
    "portfolioRevenueAed": 4674902,
    "inventoryGrowthPct": 144.0,
    "commonBedroom": "1"
  },
  {
    "name": "Monty Holiday Home",
    "website": "montyholidayhome.com",
    "listings": 34,
    "avgRating": 4.7,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 136503,
    "avgAdrAed": 1161,
    "portfolioRevenueAed": 4641107,
    "inventoryGrowthPct": 36.0,
    "commonBedroom": "1"
  },
  {
    "name": "Prestige Retreats",
    "website": "prestigeretreats.ae",
    "listings": 24,
    "avgRating": 5.0,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 192009,
    "avgAdrAed": 1113,
    "portfolioRevenueAed": 4608224,
    "inventoryGrowthPct": 166.67,
    "commonBedroom": "1"
  },
  {
    "name": "Kensington Homes",
    "website": "kensingtonhomes.ae",
    "listings": 44,
    "avgRating": 4.8,
    "avgOccupancy": 0.58,
    "avgRevenueAed": 104633,
    "avgAdrAed": 1157,
    "portfolioRevenueAed": 4603861,
    "inventoryGrowthPct": 266.67,
    "commonBedroom": "2"
  },
  {
    "name": "Golden Stays",
    "website": "goldenstays.holidayfuture.com",
    "listings": 53,
    "avgRating": 4.9,
    "avgOccupancy": 0.64,
    "avgRevenueAed": 86535,
    "avgAdrAed": 1072,
    "portfolioRevenueAed": 4586361,
    "inventoryGrowthPct": 2550.0,
    "commonBedroom": "1"
  },
  {
    "name": "Staycae",
    "website": "https://www.staycae.ae",
    "listings": 57,
    "avgRating": 4.4,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 80453,
    "avgAdrAed": 867,
    "portfolioRevenueAed": 4585847,
    "inventoryGrowthPct": 29.55,
    "commonBedroom": "1"
  },
  {
    "name": "Wonderful Stay",
    "website": "wonderfulstay.ae",
    "listings": 26,
    "avgRating": 5.0,
    "avgOccupancy": 0.79,
    "avgRevenueAed": 175902,
    "avgAdrAed": 1010,
    "portfolioRevenueAed": 4573445,
    "inventoryGrowthPct": 73.33,
    "commonBedroom": "2"
  },
  {
    "name": "Two Continents Dubai",
    "website": "twocontinents.com",
    "listings": 32,
    "avgRating": 4.9,
    "avgOccupancy": 0.82,
    "avgRevenueAed": 142893,
    "avgAdrAed": 911,
    "portfolioRevenueAed": 4572586,
    "inventoryGrowthPct": 68.42,
    "commonBedroom": "1"
  },
  {
    "name": "Farwell And Gervase",
    "website": "farwellgervase.com",
    "listings": 33,
    "avgRating": 4.9,
    "avgOccupancy": 0.76,
    "avgRevenueAed": 137006,
    "avgAdrAed": 1366,
    "portfolioRevenueAed": 4521207,
    "inventoryGrowthPct": 200.0,
    "commonBedroom": "2"
  },
  {
    "name": "B L V D Holiday Homes",
    "website": "holidayblvd.com",
    "listings": 74,
    "avgRating": 4.9,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 61074,
    "avgAdrAed": 657,
    "portfolioRevenueAed": 4519452,
    "inventoryGrowthPct": 164.29,
    "commonBedroom": "1"
  },
  {
    "name": "WhiteSage Holiday Homes",
    "website": "whitesage-dubai.com",
    "listings": 39,
    "avgRating": 4.5,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 114913,
    "avgAdrAed": 690,
    "portfolioRevenueAed": 4481588,
    "inventoryGrowthPct": 25.81,
    "commonBedroom": "1"
  },
  {
    "name": "RAD Holiday Homes",
    "website": "radholidayhomes.ae",
    "listings": 48,
    "avgRating": 4.5,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 92474,
    "avgAdrAed": 1267,
    "portfolioRevenueAed": 4438730,
    "inventoryGrowthPct": 41.18,
    "commonBedroom": "1"
  },
  {
    "name": "Bespoke Residences & Holiday Homes",
    "website": "bespokeresidences.com/",
    "listings": 48,
    "avgRating": 4.4,
    "avgOccupancy": 0.64,
    "avgRevenueAed": 91320,
    "avgAdrAed": 668,
    "portfolioRevenueAed": 4383378,
    "inventoryGrowthPct": 60.0,
    "commonBedroom": "1"
  },
  {
    "name": "EasyGo",
    "website": "easygoholidayhomes.com",
    "listings": 57,
    "avgRating": 4.4,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 76792,
    "avgAdrAed": 584,
    "portfolioRevenueAed": 4377143,
    "inventoryGrowthPct": 62.86,
    "commonBedroom": "1"
  },
  {
    "name": "Ateliero",
    "website": "linkedin.com/company/ateliero",
    "listings": 38,
    "avgRating": 4.8,
    "avgOccupancy": 0.83,
    "avgRevenueAed": 114409,
    "avgAdrAed": 613,
    "portfolioRevenueAed": 4347557,
    "inventoryGrowthPct": 35.71,
    "commonBedroom": "1"
  },
  {
    "name": "Keys Please Holiday Homes Dubai",
    "website": "keysplease.ae",
    "listings": 27,
    "avgRating": 4.9,
    "avgOccupancy": 0.64,
    "avgRevenueAed": 159240,
    "avgAdrAed": 1392,
    "portfolioRevenueAed": 4299469,
    "inventoryGrowthPct": 8.0,
    "commonBedroom": "1"
  },
  {
    "name": "Baron Luxe Stays",
    "website": "instagram.com/baronluxestays",
    "listings": 25,
    "avgRating": 4.9,
    "avgOccupancy": 0.72,
    "avgRevenueAed": 169552,
    "avgAdrAed": 1006,
    "portfolioRevenueAed": 4238800,
    "inventoryGrowthPct": 66.67,
    "commonBedroom": "0"
  },
  {
    "name": "SuperHost Vacation Homes Rental",
    "website": "superhost.ae",
    "listings": 31,
    "avgRating": 4.4,
    "avgOccupancy": 0.59,
    "avgRevenueAed": 136698,
    "avgAdrAed": 925,
    "portfolioRevenueAed": 4237632,
    "inventoryGrowthPct": 34.78,
    "commonBedroom": "0"
  },
  {
    "name": "BellaVista",
    "website": "bellavista.ae",
    "listings": 22,
    "avgRating": 4.2,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 189071,
    "avgAdrAed": 914,
    "portfolioRevenueAed": 4159569,
    "inventoryGrowthPct": 15.79,
    "commonBedroom": "1"
  },
  {
    "name": "Sunrise Vacation Homes",
    "website": "sunrisevacationhomes.ae",
    "listings": 40,
    "avgRating": 4.8,
    "avgOccupancy": 0.77,
    "avgRevenueAed": 103983,
    "avgAdrAed": 635,
    "portfolioRevenueAed": 4159327,
    "inventoryGrowthPct": 48.15,
    "commonBedroom": "1"
  },
  {
    "name": "Acerca de Qstay",
    "website": "qstay.be",
    "listings": 42,
    "avgRating": 4.8,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 98441,
    "avgAdrAed": 1234,
    "portfolioRevenueAed": 4134537,
    "inventoryGrowthPct": 5.0,
    "commonBedroom": "2"
  },
  {
    "name": "Homevy",
    "website": "homevy.com/?srsltid=AfmBOorbLVRrQaGO1CLeqOLG-GIsVWCp5-b_28QtKujF1_GjXRz4pSqW",
    "listings": 30,
    "avgRating": 4.8,
    "avgOccupancy": 0.78,
    "avgRevenueAed": 137557,
    "avgAdrAed": 959,
    "portfolioRevenueAed": 4126715,
    "inventoryGrowthPct": 76.47,
    "commonBedroom": "1"
  },
  {
    "name": "Mi Casa Holiday Homes",
    "website": "micasaholidayhomes.com",
    "listings": 39,
    "avgRating": 4.9,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 104975,
    "avgAdrAed": 771,
    "portfolioRevenueAed": 4094015,
    "inventoryGrowthPct": 11.43,
    "commonBedroom": "0"
  },
  {
    "name": "Venduras Holiday Homes",
    "website": "venduras.com",
    "listings": 30,
    "avgRating": 4.8,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 136213,
    "avgAdrAed": 1344,
    "portfolioRevenueAed": 4086391,
    "inventoryGrowthPct": 15.38,
    "commonBedroom": "1"
  },
  {
    "name": "\u2068Carlos A.\u2069",
    "website": "rentalho.com",
    "listings": 37,
    "avgRating": 4.7,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 104839,
    "avgAdrAed": 819,
    "portfolioRevenueAed": 3879038,
    "inventoryGrowthPct": 76.19,
    "commonBedroom": "1"
  },
  {
    "name": "Homes Beyond",
    "website": "homesbeyond.ae",
    "listings": 36,
    "avgRating": 4.4,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 107568,
    "avgAdrAed": 764,
    "portfolioRevenueAed": 3872431,
    "inventoryGrowthPct": 20.0,
    "commonBedroom": "1"
  },
  {
    "name": "Citi-Home",
    "website": "citihome.ae",
    "listings": 61,
    "avgRating": 4.7,
    "avgOccupancy": 0.75,
    "avgRevenueAed": 62124,
    "avgAdrAed": 635,
    "portfolioRevenueAed": 3789565,
    "inventoryGrowthPct": 79.41,
    "commonBedroom": "1"
  },
  {
    "name": "Elysee Vendome",
    "website": "elyseevendome-holidayhomes.com",
    "listings": 51,
    "avgRating": 4.8,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 71779,
    "avgAdrAed": 610,
    "portfolioRevenueAed": 3660730,
    "inventoryGrowthPct": 45.71,
    "commonBedroom": "1"
  },
  {
    "name": "Rezotels",
    "website": "rezotels.com",
    "listings": 99,
    "avgRating": 4.3,
    "avgOccupancy": 0.53,
    "avgRevenueAed": 36898,
    "avgAdrAed": 334,
    "portfolioRevenueAed": 3652863,
    "inventoryGrowthPct": 22.22,
    "commonBedroom": "1"
  },
  {
    "name": "Rove Haven",
    "website": "rovehaven.com",
    "listings": 35,
    "avgRating": 4.9,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 104141,
    "avgAdrAed": 863,
    "portfolioRevenueAed": 3644938,
    "inventoryGrowthPct": 133.33,
    "commonBedroom": "1"
  },
  {
    "name": "Airstay Holiday Homes",
    "website": "airstay.ae",
    "listings": 46,
    "avgRating": 4.8,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 78995,
    "avgAdrAed": 812,
    "portfolioRevenueAed": 3633792,
    "inventoryGrowthPct": 360.0,
    "commonBedroom": "1"
  },
  {
    "name": "New Arabian Holiday Homes",
    "website": "http://newarabianholidayhomes.com",
    "listings": 34,
    "avgRating": 4.7,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 106734,
    "avgAdrAed": 1388,
    "portfolioRevenueAed": 3628951,
    "inventoryGrowthPct": 61.9,
    "commonBedroom": "2"
  },
  {
    "name": "Hello Bnb",
    "website": "hellobnb.ae",
    "listings": 52,
    "avgRating": 5.0,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 69363,
    "avgAdrAed": 628,
    "portfolioRevenueAed": 3606850,
    "inventoryGrowthPct": 92.59,
    "commonBedroom": "1"
  },
  {
    "name": "Rich Stay Holiday Homes LLC",
    "website": "richstay.ae",
    "listings": 26,
    "avgRating": 4.7,
    "avgOccupancy": 0.69,
    "avgRevenueAed": 138163,
    "avgAdrAed": 845,
    "portfolioRevenueAed": 3592241,
    "inventoryGrowthPct": 13.04,
    "commonBedroom": "1"
  },
  {
    "name": "Be My Guest Holiday Homes",
    "website": "bmyguest.ae",
    "listings": 38,
    "avgRating": 0.0,
    "avgOccupancy": 0.53,
    "avgRevenueAed": 94306,
    "avgAdrAed": 1234,
    "portfolioRevenueAed": 3583633,
    "inventoryGrowthPct": 35.71,
    "commonBedroom": "1"
  },
  {
    "name": "V Edition Holiday Homes Rental LLC",
    "website": "vedition.ae",
    "listings": 29,
    "avgRating": 4.3,
    "avgOccupancy": 0.56,
    "avgRevenueAed": 119165,
    "avgAdrAed": 1025,
    "portfolioRevenueAed": 3455793,
    "inventoryGrowthPct": 70.59,
    "commonBedroom": "2"
  },
  {
    "name": "McCone Living",
    "website": "mcconeliving.com",
    "listings": 30,
    "avgRating": 4.8,
    "avgOccupancy": 0.83,
    "avgRevenueAed": 112691,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 3380720,
    "inventoryGrowthPct": 15.38,
    "commonBedroom": "1"
  },
  {
    "name": "Stonetree Holiday Homes",
    "website": "stonetree.ae",
    "listings": 72,
    "avgRating": 4.9,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 45242,
    "avgAdrAed": 830,
    "portfolioRevenueAed": 3257390,
    "inventoryGrowthPct": 928.57,
    "commonBedroom": "1"
  },
  {
    "name": "Aya Boutique",
    "website": "ayaboutique.ae",
    "listings": 27,
    "avgRating": 4.9,
    "avgOccupancy": 0.78,
    "avgRevenueAed": 120546,
    "avgAdrAed": 749,
    "portfolioRevenueAed": 3254746,
    "inventoryGrowthPct": 58.82,
    "commonBedroom": "1"
  },
  {
    "name": "Amber Holiday",
    "website": "amberholidayhomes.com",
    "listings": 40,
    "avgRating": 4.7,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 80619,
    "avgAdrAed": 1528,
    "portfolioRevenueAed": 3224749,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "1"
  },
  {
    "name": "Bnbeyond",
    "website": "bnbeyond.ae",
    "listings": 40,
    "avgRating": 4.9,
    "avgOccupancy": 0.69,
    "avgRevenueAed": 80483,
    "avgAdrAed": 768,
    "portfolioRevenueAed": 3219314,
    "inventoryGrowthPct": 300.0,
    "commonBedroom": "1"
  },
  {
    "name": "Magnificent Homes",
    "website": "magnificent.ae",
    "listings": 27,
    "avgRating": 4.9,
    "avgOccupancy": 0.75,
    "avgRevenueAed": 118824,
    "avgAdrAed": 760,
    "portfolioRevenueAed": 3208241,
    "inventoryGrowthPct": 3.85,
    "commonBedroom": "2"
  },
  {
    "name": "Lux",
    "website": "luxtravels.com",
    "listings": 33,
    "avgRating": 4.5,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 96605,
    "avgAdrAed": 790,
    "portfolioRevenueAed": 3187969,
    "inventoryGrowthPct": 22.22,
    "commonBedroom": "2"
  },
  {
    "name": "APAL Holiday Homes Rental",
    "website": "apal.ae",
    "listings": 28,
    "avgRating": 4.8,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 112970,
    "avgAdrAed": 925,
    "portfolioRevenueAed": 3163154,
    "inventoryGrowthPct": 64.71,
    "commonBedroom": "2"
  },
  {
    "name": "Ustay",
    "website": "ustay.ae",
    "listings": 31,
    "avgRating": 4.8,
    "avgOccupancy": 0.79,
    "avgRevenueAed": 101879,
    "avgAdrAed": 856,
    "portfolioRevenueAed": 3158243,
    "inventoryGrowthPct": 29.17,
    "commonBedroom": "0"
  },
  {
    "name": "Only Stays",
    "website": "onlystays.net",
    "listings": 30,
    "avgRating": 4.9,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 104101,
    "avgAdrAed": 992,
    "portfolioRevenueAed": 3123021,
    "inventoryGrowthPct": 328.57,
    "commonBedroom": "1"
  },
  {
    "name": "Hideaway Vacation Homes Rental",
    "website": "staywithhideaway.com",
    "listings": 32,
    "avgRating": 4.5,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 97292,
    "avgAdrAed": 705,
    "portfolioRevenueAed": 3113340,
    "inventoryGrowthPct": 88.24,
    "commonBedroom": "1"
  },
  {
    "name": "Gala Guests",
    "website": "galaguests.com",
    "listings": 37,
    "avgRating": 4.9,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 84034,
    "avgAdrAed": 742,
    "portfolioRevenueAed": 3109263,
    "inventoryGrowthPct": 208.33,
    "commonBedroom": "1"
  },
  {
    "name": "Landhouse Holiday Homes",
    "website": "landhouseholidays.com",
    "listings": 24,
    "avgRating": 4.8,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 129033,
    "avgAdrAed": 723,
    "portfolioRevenueAed": 3096799,
    "inventoryGrowthPct": 26.32,
    "commonBedroom": "1"
  },
  {
    "name": "Ivy Luxury Holiday Homes",
    "website": "ivyluxury.ae",
    "listings": 48,
    "avgRating": 4.6,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 62936,
    "avgAdrAed": 470,
    "portfolioRevenueAed": 3020910,
    "inventoryGrowthPct": 71.43,
    "commonBedroom": "0"
  },
  {
    "name": "Zuko Home Square",
    "website": "homesquarerealestate.com",
    "listings": 32,
    "avgRating": 4.5,
    "avgOccupancy": 0.52,
    "avgRevenueAed": 93752,
    "avgAdrAed": 738,
    "portfolioRevenueAed": 3000051,
    "inventoryGrowthPct": 23.08,
    "commonBedroom": "2"
  },
  {
    "name": "Alashrafia Saray Vacation Homes",
    "website": "alashrafiasaray.com",
    "listings": 30,
    "avgRating": 4.5,
    "avgOccupancy": 0.71,
    "avgRevenueAed": 94655,
    "avgAdrAed": 521,
    "portfolioRevenueAed": 2839650,
    "inventoryGrowthPct": 50.0,
    "commonBedroom": "1"
  },
  {
    "name": "Casa Royale Holiday Homes",
    "website": "casaroyale.ae",
    "listings": 27,
    "avgRating": 4.7,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 102753,
    "avgAdrAed": 870,
    "portfolioRevenueAed": 2774328,
    "inventoryGrowthPct": 12.5,
    "commonBedroom": "1"
  },
  {
    "name": "Escape24 Vacation Homes Rental",
    "website": "escape24.ae",
    "listings": 37,
    "avgRating": 4.5,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 74438,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 2754202,
    "inventoryGrowthPct": 105.56,
    "commonBedroom": "1"
  },
  {
    "name": "ELAN Suites",
    "website": "elansuites.com",
    "listings": 23,
    "avgRating": 4.6,
    "avgOccupancy": 0.26,
    "avgRevenueAed": 118989,
    "avgAdrAed": 3004,
    "portfolioRevenueAed": 2736747,
    "inventoryGrowthPct": 43.75,
    "commonBedroom": "6"
  },
  {
    "name": "Bloomfields Holiday Homes",
    "website": "bfliving.com",
    "listings": 74,
    "avgRating": 3.9,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 36490,
    "avgAdrAed": 521,
    "portfolioRevenueAed": 2700257,
    "inventoryGrowthPct": 174.07,
    "commonBedroom": "0"
  },
  {
    "name": "Tranquil Boutique",
    "website": "tranquilboutique.com",
    "listings": 23,
    "avgRating": 4.8,
    "avgOccupancy": 0.64,
    "avgRevenueAed": 115845,
    "avgAdrAed": 738,
    "portfolioRevenueAed": 2664443,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "1"
  },
  {
    "name": "DAIFY Vacation Homes",
    "website": "daifyhomes.com",
    "listings": 34,
    "avgRating": 4.8,
    "avgOccupancy": 0.76,
    "avgRevenueAed": 77949,
    "avgAdrAed": 496,
    "portfolioRevenueAed": 2650260,
    "inventoryGrowthPct": 21.43,
    "commonBedroom": "1"
  },
  {
    "name": "Naseem Holiday Homes",
    "website": "naseem.homes",
    "listings": 28,
    "avgRating": 4.6,
    "avgOccupancy": 0.62,
    "avgRevenueAed": 94479,
    "avgAdrAed": 760,
    "portfolioRevenueAed": 2645405,
    "inventoryGrowthPct": 86.67,
    "commonBedroom": "1"
  },
  {
    "name": "Raine & Horne",
    "website": "http://www.rhdubai.ae",
    "listings": 48,
    "avgRating": 4.0,
    "avgOccupancy": 0.46,
    "avgRevenueAed": 54074,
    "avgAdrAed": 705,
    "portfolioRevenueAed": 2595547,
    "inventoryGrowthPct": 26.32,
    "commonBedroom": "1"
  },
  {
    "name": "Home Resort",
    "website": "resortpropertiesidaho.com",
    "listings": 23,
    "avgRating": 4.8,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 110711,
    "avgAdrAed": 834,
    "portfolioRevenueAed": 2546357,
    "inventoryGrowthPct": 43.75,
    "commonBedroom": "2"
  },
  {
    "name": "BellaCasa",
    "website": "bellwether.house",
    "listings": 43,
    "avgRating": 4.5,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 58040,
    "avgAdrAed": 955,
    "portfolioRevenueAed": 2495728,
    "inventoryGrowthPct": 48.28,
    "commonBedroom": "1"
  },
  {
    "name": "Ultimate Stay",
    "website": "ultimate-stay.com",
    "listings": 24,
    "avgRating": 4.8,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 103491,
    "avgAdrAed": 984,
    "portfolioRevenueAed": 2483785,
    "inventoryGrowthPct": 4.35,
    "commonBedroom": "2"
  },
  {
    "name": "Pure Living Holiday Homes",
    "website": "pureliving.ae",
    "listings": 38,
    "avgRating": 4.4,
    "avgOccupancy": 0.5,
    "avgRevenueAed": 64974,
    "avgAdrAed": 841,
    "portfolioRevenueAed": 2469007,
    "inventoryGrowthPct": 26.67,
    "commonBedroom": "1"
  },
  {
    "name": "Utopia Holiday Homes",
    "website": "utopiaholidayhome.com",
    "listings": 28,
    "avgRating": 4.4,
    "avgOccupancy": 0.69,
    "avgRevenueAed": 86105,
    "avgAdrAed": 760,
    "portfolioRevenueAed": 2410952,
    "inventoryGrowthPct": 47.37,
    "commonBedroom": "1"
  },
  {
    "name": "HolidayStay",
    "website": "holidaystays.com/contact-holiday-stays",
    "listings": 20,
    "avgRating": 4.4,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 120083,
    "avgAdrAed": 720,
    "portfolioRevenueAed": 2401668,
    "inventoryGrowthPct": 81.82,
    "commonBedroom": "1"
  },
  {
    "name": "Enklo Vacation Homes",
    "website": "facebook.com/profile.php?id=61553012884648",
    "listings": 24,
    "avgRating": 5.0,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 96767,
    "avgAdrAed": 606,
    "portfolioRevenueAed": 2322401,
    "inventoryGrowthPct": 14.29,
    "commonBedroom": "1"
  },
  {
    "name": "Mystic Holiday Homes Rentals LLC",
    "website": "mysticholidayhomes.com",
    "listings": 27,
    "avgRating": 4.3,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 85738,
    "avgAdrAed": 577,
    "portfolioRevenueAed": 2314931,
    "inventoryGrowthPct": 8.0,
    "commonBedroom": "0"
  },
  {
    "name": "Oskena Homes",
    "website": "oskena.com",
    "listings": 54,
    "avgRating": 4.9,
    "avgOccupancy": 0.46,
    "avgRevenueAed": 42417,
    "avgAdrAed": 1528,
    "portfolioRevenueAed": 2290538,
    "inventoryGrowthPct": 285.71,
    "commonBedroom": "1"
  },
  {
    "name": "One Perfect Stay",
    "website": "oneperfectstay.com",
    "listings": 37,
    "avgRating": 4.4,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 61419,
    "avgAdrAed": 536,
    "portfolioRevenueAed": 2272499,
    "inventoryGrowthPct": 42.31,
    "commonBedroom": "1"
  },
  {
    "name": "Elite LUX Holiday Homes",
    "website": "eliteluxhomes.ae",
    "listings": 31,
    "avgRating": 4.8,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 72124,
    "avgAdrAed": 679,
    "portfolioRevenueAed": 2235851,
    "inventoryGrowthPct": 47.62,
    "commonBedroom": "1"
  },
  {
    "name": "Ofex Holiday Homes",
    "website": "ofexholidayhome.com",
    "listings": 45,
    "avgRating": 4.7,
    "avgOccupancy": 0.5,
    "avgRevenueAed": 49292,
    "avgAdrAed": 734,
    "portfolioRevenueAed": 2218153,
    "inventoryGrowthPct": 221.43,
    "commonBedroom": "1"
  },
  {
    "name": "Zilal Vacation",
    "website": "instagram.com/zilal_vacation",
    "listings": 26,
    "avgRating": 4.4,
    "avgOccupancy": 0.57,
    "avgRevenueAed": 84706,
    "avgAdrAed": 757,
    "portfolioRevenueAed": 2202362,
    "inventoryGrowthPct": 4.0,
    "commonBedroom": "1"
  },
  {
    "name": "Millennium Vacation Homes",
    "website": "instagram.com/millennium.vacation.homes",
    "listings": 20,
    "avgRating": 4.6,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 110054,
    "avgAdrAed": 734,
    "portfolioRevenueAed": 2201076,
    "inventoryGrowthPct": 11.11,
    "commonBedroom": "1"
  },
  {
    "name": "Livin' Holidays",
    "website": "livinexperts.ae",
    "listings": 24,
    "avgRating": 4.8,
    "avgOccupancy": 0.75,
    "avgRevenueAed": 89727,
    "avgAdrAed": 764,
    "portfolioRevenueAed": 2153436,
    "inventoryGrowthPct": 380.0,
    "commonBedroom": "0"
  },
  {
    "name": "Shores Inn Holiday Homes Rental L.L.C",
    "website": "shoresinn.ae",
    "listings": 25,
    "avgRating": 4.7,
    "avgOccupancy": 0.56,
    "avgRevenueAed": 85173,
    "avgAdrAed": 768,
    "portfolioRevenueAed": 2129316,
    "inventoryGrowthPct": 47.06,
    "commonBedroom": "1"
  },
  {
    "name": "NOVA Holiday Homes",
    "website": "instagram.com/novaholidayhomes_dubai",
    "listings": 35,
    "avgRating": 4.8,
    "avgOccupancy": 0.56,
    "avgRevenueAed": 59682,
    "avgAdrAed": 878,
    "portfolioRevenueAed": 2088863,
    "inventoryGrowthPct": 16.67,
    "commonBedroom": "1"
  },
  {
    "name": "Veluxa Holiday Homes",
    "website": "veluxa.net",
    "listings": 36,
    "avgRating": 4.8,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 54210,
    "avgAdrAed": 687,
    "portfolioRevenueAed": 1951552,
    "inventoryGrowthPct": 176.92,
    "commonBedroom": "2"
  },
  {
    "name": "Luxe Shortlet Holiday Homes",
    "website": "luxeshortlet.ae",
    "listings": 24,
    "avgRating": 4.9,
    "avgOccupancy": 0.74,
    "avgRevenueAed": 79638,
    "avgAdrAed": 1205,
    "portfolioRevenueAed": 1911316,
    "inventoryGrowthPct": 4.35,
    "commonBedroom": "1"
  },
  {
    "name": "Zed Living",
    "website": "zedliving.ae",
    "listings": 20,
    "avgRating": 4.9,
    "avgOccupancy": 0.73,
    "avgRevenueAed": 95525,
    "avgAdrAed": 621,
    "portfolioRevenueAed": 1910508,
    "inventoryGrowthPct": 11.11,
    "commonBedroom": "1"
  },
  {
    "name": "Vibel Stay",
    "website": "vibelstay.holidayfuture.com",
    "listings": 36,
    "avgRating": 4.7,
    "avgOccupancy": 0.58,
    "avgRevenueAed": 53020,
    "avgAdrAed": 632,
    "portfolioRevenueAed": 1908716,
    "inventoryGrowthPct": 50.0,
    "commonBedroom": "1"
  },
  {
    "name": "Glidai Holiday Homes",
    "website": "glidai-homes.com",
    "listings": 20,
    "avgRating": 4.9,
    "avgOccupancy": 0.8,
    "avgRevenueAed": 94218,
    "avgAdrAed": 566,
    "portfolioRevenueAed": 1884360,
    "inventoryGrowthPct": 66.67,
    "commonBedroom": "1"
  },
  {
    "name": "Chalet Holiday Homes",
    "website": "chalethomes.ae",
    "listings": 22,
    "avgRating": 4.5,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 85015,
    "avgAdrAed": 837,
    "portfolioRevenueAed": 1870323,
    "inventoryGrowthPct": 175.0,
    "commonBedroom": "1"
  },
  {
    "name": "Desert City Stays",
    "website": "desertcitystays.com",
    "listings": 25,
    "avgRating": 4.9,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 73711,
    "avgAdrAed": 694,
    "portfolioRevenueAed": 1842769,
    "inventoryGrowthPct": 25.0,
    "commonBedroom": "1"
  },
  {
    "name": "Boosting Real Estate & Holiday Homes",
    "website": "facebook.com/BOOSTING.GROUP",
    "listings": 22,
    "avgRating": 4.3,
    "avgOccupancy": 0.65,
    "avgRevenueAed": 83520,
    "avgAdrAed": 903,
    "portfolioRevenueAed": 1837440,
    "inventoryGrowthPct": 37.5,
    "commonBedroom": "1"
  },
  {
    "name": "Ashri Holiday Homes",
    "website": "ashriproperties.com",
    "listings": 31,
    "avgRating": 4.5,
    "avgOccupancy": 0.76,
    "avgRevenueAed": 56153,
    "avgAdrAed": 459,
    "portfolioRevenueAed": 1740728,
    "inventoryGrowthPct": 29.17,
    "commonBedroom": "1"
  },
  {
    "name": "My Holiday Vacation Homes",
    "website": "mymymy.group",
    "listings": 31,
    "avgRating": 4.5,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 55940,
    "avgAdrAed": 874,
    "portfolioRevenueAed": 1734125,
    "inventoryGrowthPct": 93.75,
    "commonBedroom": "1"
  },
  {
    "name": "Luxovista Holiday Homes",
    "website": "luxovista.holidayfuture.com",
    "listings": 21,
    "avgRating": 4.7,
    "avgOccupancy": 0.5,
    "avgRevenueAed": 82517,
    "avgAdrAed": 797,
    "portfolioRevenueAed": 1732865,
    "inventoryGrowthPct": 61.54,
    "commonBedroom": "1"
  },
  {
    "name": "One Address Holiday Homes",
    "website": "oneaddressdubai.com",
    "listings": 29,
    "avgRating": 4.8,
    "avgOccupancy": 0.72,
    "avgRevenueAed": 59465,
    "avgAdrAed": 694,
    "portfolioRevenueAed": 1724488,
    "inventoryGrowthPct": 107.14,
    "commonBedroom": "1"
  },
  {
    "name": "Richmond Vacation Homes Rental",
    "website": "instagram.com/richmondhomesrental/reels",
    "listings": 29,
    "avgRating": 4.8,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 56692,
    "avgAdrAed": 503,
    "portfolioRevenueAed": 1644079,
    "inventoryGrowthPct": 31.82,
    "commonBedroom": "1"
  },
  {
    "name": "Medait Star Holidays",
    "website": "abysek.com",
    "listings": 28,
    "avgRating": 4.7,
    "avgOccupancy": 0.41,
    "avgRevenueAed": 55741,
    "avgAdrAed": 768,
    "portfolioRevenueAed": 1560754,
    "inventoryGrowthPct": 12.0,
    "commonBedroom": "1"
  },
  {
    "name": "Exclusive Links Vacation Homes",
    "website": "exclusive-links.com",
    "listings": 32,
    "avgRating": 4.7,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 47889,
    "avgAdrAed": 749,
    "portfolioRevenueAed": 1532461,
    "inventoryGrowthPct": 39.13,
    "commonBedroom": "2"
  },
  {
    "name": "DXBStayz",
    "website": "dxbstayz.ae",
    "listings": 25,
    "avgRating": 4.8,
    "avgOccupancy": 0.68,
    "avgRevenueAed": 61287,
    "avgAdrAed": 668,
    "portfolioRevenueAed": 1532167,
    "inventoryGrowthPct": 19.05,
    "commonBedroom": "1"
  },
  {
    "name": "Tanami Holiday Homes",
    "website": "instagram.com/tanamiholidayhomes",
    "listings": 25,
    "avgRating": 4.2,
    "avgOccupancy": 0.58,
    "avgRevenueAed": 59171,
    "avgAdrAed": 727,
    "portfolioRevenueAed": 1479283,
    "inventoryGrowthPct": 31.58,
    "commonBedroom": "1"
  },
  {
    "name": "Elegant Escapes",
    "website": "elegantescapes.com",
    "listings": 20,
    "avgRating": 4.7,
    "avgOccupancy": 0.67,
    "avgRevenueAed": 73872,
    "avgAdrAed": 690,
    "portfolioRevenueAed": 1477447,
    "inventoryGrowthPct": 185.71,
    "commonBedroom": "1"
  },
  {
    "name": "Rare Holiday Homes",
    "website": "instagram.com/rareholidayhomes",
    "listings": 29,
    "avgRating": 4.4,
    "avgOccupancy": 0.72,
    "avgRevenueAed": 50379,
    "avgAdrAed": 349,
    "portfolioRevenueAed": 1461001,
    "inventoryGrowthPct": 20.83,
    "commonBedroom": "0"
  },
  {
    "name": "Lets Rent Dubai",
    "website": "letsrentdubai.com",
    "listings": 34,
    "avgRating": 4.6,
    "avgOccupancy": 0.55,
    "avgRevenueAed": 39593,
    "avgAdrAed": 676,
    "portfolioRevenueAed": 1346170,
    "inventoryGrowthPct": 78.95,
    "commonBedroom": "1"
  },
  {
    "name": "Colife",
    "website": "colife.ae",
    "listings": 41,
    "avgRating": 4.8,
    "avgOccupancy": 0.51,
    "avgRevenueAed": 31345,
    "avgAdrAed": 628,
    "portfolioRevenueAed": 1285136,
    "inventoryGrowthPct": 156.25,
    "commonBedroom": "1"
  },
  {
    "name": "Icon Casa Living",
    "website": "iconcasaliving.com",
    "listings": 44,
    "avgRating": 4.7,
    "avgOccupancy": 0.7,
    "avgRevenueAed": 28623,
    "avgAdrAed": 393,
    "portfolioRevenueAed": 1259432,
    "inventoryGrowthPct": 51.72,
    "commonBedroom": "0"
  },
  {
    "name": "P.K. Holidays",
    "website": "pkholidays.ae",
    "listings": 48,
    "avgRating": 4.8,
    "avgOccupancy": 0.63,
    "avgRevenueAed": 23702,
    "avgAdrAed": 698,
    "portfolioRevenueAed": 1137711,
    "inventoryGrowthPct": 65.52,
    "commonBedroom": "1"
  },
  {
    "name": "RoomAko",
    "website": "facebook.com/GBVHotelDubai",
    "listings": 42,
    "avgRating": 4.3,
    "avgOccupancy": 0.32,
    "avgRevenueAed": 25968,
    "avgAdrAed": 389,
    "portfolioRevenueAed": 1090666,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "1"
  },
  {
    "name": "AIRAS",
    "website": "airashomerental.com",
    "listings": 44,
    "avgRating": 4.2,
    "avgOccupancy": 0.61,
    "avgRevenueAed": 22869,
    "avgAdrAed": 422,
    "portfolioRevenueAed": 1006221,
    "inventoryGrowthPct": 91.3,
    "commonBedroom": "1"
  },
  {
    "name": "Brown Stone Holiday Homes",
    "website": "bsholidayhomes.com",
    "listings": 20,
    "avgRating": 4.0,
    "avgOccupancy": 0.56,
    "avgRevenueAed": 43754,
    "avgAdrAed": 525,
    "portfolioRevenueAed": 875083,
    "inventoryGrowthPct": 25.0,
    "commonBedroom": "1"
  },
  {
    "name": "Shellgrow Holiday Homes",
    "website": "shellgrow.com",
    "listings": 34,
    "avgRating": 4.6,
    "avgOccupancy": 0.6,
    "avgRevenueAed": 19787,
    "avgAdrAed": 470,
    "portfolioRevenueAed": 672773,
    "inventoryGrowthPct": 78.95,
    "commonBedroom": "1"
  },
  {
    "name": "Stay By AlGhurair",
    "website": "al-ghurair.com",
    "listings": 39,
    "avgRating": 4.8,
    "avgOccupancy": 0.0,
    "avgRevenueAed": null,
    "avgAdrAed": null,
    "portfolioRevenueAed": null,
    "inventoryGrowthPct": 0.0,
    "commonBedroom": "1"
  }
];
