/**
 * OPERATOR INTELLIGENCE DATABASE
 * Source: dubai_holiday_home_operators_knowledge_base.csv
 * 100+ operators organized by tier and specialization
 *
 * This file contains the enhanced operator data with tier classification,
 * portfolio metrics, and strength tags for intelligent matching
 */

export interface OperatorCSVData {
  operator_id: string;
  name: string;
  tier: string;
  est_commission_pct: string;
  min_commission: number;
  max_commission: number;
  portfolio_size_units: string;
  portfolio_value_aed: string;
  years_in_business: string;
  preferred_locations: string;
  optimal_bedroom_types: string;
  payout_cycle_day: string;
  strengths_tags: string;
  company_profile: string;
}

/**
 * Helper function to parse commission percentage string
 * "15%-20%" → [15, 20]
 */
export function parseCommission(commStr: string): [number, number] {
  const match = commStr.match(/(\d+)%?-?(\d+)%/);
  if (match) {
    return [parseInt(match[1]), parseInt(match[2])];
  }
  const single = commStr.match(/(\d+)%/);
  if (single) {
    const val = parseInt(single[1]);
    return [val, val];
  }
  return [15, 20]; // default
}

/**
 * Helper function to parse portfolio size
 * "820+" → 820
 * "1400+ (Regional/Global)" → 1400
 */
export function parsePortfolioSize(sizeStr: string): number {
  const match = sizeStr.match(/(\d+)/);
  return match ? parseInt(match[1]) : 0;
}

/**
 * Helper function to parse years in business
 * "10+" → 10
 * "Established" → 5
 */
export function parseYearsInBusiness(yearsStr: string): number {
  const match = yearsStr.match(/(\d+)/);
  if (match) return parseInt(match[1]);
  if (yearsStr.toLowerCase().includes("established")) return 5;
  if (yearsStr.toLowerCase().includes("startup")) return 1;
  return 2;
}

/**
 * Parse strengths tags from comma-separated string
 */
export function parseStrengths(tagsStr: string): string[] {
  return tagsStr.split(',').map(t => t.trim()).filter(t => t.length > 0);
}

/**
 * Parse optimal bedroom types from comma-separated string
 */
export function parseBedroomTypes(typesStr: string): string[] {
  return typesStr.split(',').map(t => t.trim()).filter(t => t.length > 0);
}

/**
 * Parse preferred locations from comma-separated string
 */
export function parseLocations(locStr: string): string[] {
  return locStr.split(',').map(l => l.trim()).filter(l => l.length > 0);
}

/**
 * Determine tier classification for matching
 * Maps CSV tier to internal system tier
 */
export function determineTierLevel(tierStr: string): "mid" | "luxury" | "ultra-luxury" {
  if (tierStr.includes("Luxury Boutique") || tierStr.includes("Ultra")) {
    return "ultra-luxury";
  }
  if (tierStr.includes("Institutional") || tierStr.includes("Tier 1")) {
    return "luxury";
  }
  return "mid";
}

/**
 * Comprehensive CSV-to-Operator converter
 */
export function convertCSVToOperator(csvData: OperatorCSVData): any {
  const commission = parseCommission(csvData.est_commission_pct);
  const portfolio = parsePortfolioSize(csvData.portfolio_size_units);
  const years = parseYearsInBusiness(csvData.years_in_business);
  const strengths = parseStrengths(csvData.strengths_tags);
  const locations = parseLocations(csvData.preferred_locations);
  const bedrooms = parseBedroomTypes(csvData.optimal_bedroom_types);
  const internalTier = determineTierLevel(csvData.tier);

  return {
    id: csvData.operator_id,
    name: csvData.name,
    tagline: csvData.company_profile.split('.')[0] || csvData.name,
    founded: new Date().getFullYear() - years,
    commission,
    minStandard: bedrooms.length > 0 ? `Optimal for: ${bedrooms[0]}` : "Fully furnished",
    onboardingWeeks: years >= 10 ? 2 : years >= 5 ? 3 : 4,
    portfolio,
    googleRating: 4.5, // Will need to be populated separately
    googleReviewCount: 0,
    ota: [],
    bestFor: strengths.slice(0, 3),
    communities: locations,
    unitTypes: ["Apartment", "Villa"],
    minTier: internalTier,
    pros: strengths,
    cons: [],
    recentReviews: [],
    // Enhanced fields
    tier: csvData.tier,
    portfolioValue: csvData.portfolio_value_aed,
    yearsInBusiness: csvData.years_in_business,
    optimalBedroomTypes: bedrooms,
    payoutCycleDay: csvData.payout_cycle_day,
    strengthsTags: strengths,
    companyProfile: csvData.company_profile,
  };
}

/**
 * Raw operator data from CSV (100+ operators by tier)
 * This is the authoritative source for operator intelligence
 */
export const OPERATOR_CSV_DATA: OperatorCSVData[] = [
  // Tier 1: Institutional Market Leaders
  {
    operator_id: "deluxe_holiday_homes",
    name: "Deluxe Holiday Homes",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "820+",
    portfolio_value_aed: "1,700,000,000+",
    years_in_business: "10+",
    preferred_locations: "Dubai Marina, JBR, Palm Jumeirah, Downtown, Business Bay, Fujairah",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR, Luxury Villas",
    payout_cycle_day: "15th of each month",
    strengths_tags: "High Volume, Advanced Tech Stack, Award-Winning, Dynamic Pricing, Global Marketing, Multi-Office Operations",
    company_profile: "Voted Best Holiday Homes Company in UAE. Accommodated 300k+ guests across 700k+ booked nights. Holds 75%-97% occupancy using massive cross-platform syndication and an internal owner transparency portal.",
  },
  {
    operator_id: "first_class_vacation_homes",
    name: "First Class Vacation Homes",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "200+",
    portfolio_value_aed: "Premium Assets",
    years_in_business: "6",
    preferred_locations: "Downtown, DIFC, Dubai Creek Harbour, Dubai Harbour, Bluewaters, Dubai Marina, Palm Jumeirah",
    optimal_bedroom_types: "1BR, 2BR, 3BR, Luxury Penthouses, Premium Beachfront Units",
    payout_cycle_day: "15th (Statements on 10th)",
    strengths_tags: "AI Pricing Engine, 5-Star Trained Staff, Exceptional Occupancy, Premium Staging, High Review Scores",
    company_profile: "Founded in 2020 by Aeronautical and Mechanical Engineering strategy consultants. Maintains a 97.8% average review score across 3000+ bookings from 100+ countries with year-round occupancy exceeding 90%.",
  },
  {
    operator_id: "frank_porter",
    name: "Frank Porter",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "17% Flat",
    min_commission: 17.0,
    max_commission: 17.0,
    portfolio_size_units: "650+",
    portfolio_value_aed: "Mid-to-High Scale",
    years_in_business: "9",
    preferred_locations: "Downtown, Dubai Marina, JBR, Business Bay, Greens, JLT",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly Variable",
    strengths_tags: "Flat Fee Transparency, Design Focused, First-Time Hosts, Great App Tracking",
    company_profile: "Founded in 2017, heavily engineered toward simplified onboarding for first-time Airbnb hosts. Offers end-to-end premium interior design packages and strong app tracking for owners.",
  },
  {
    operator_id: "guestready",
    name: "GuestReady",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "17%-20%",
    min_commission: 17.0,
    max_commission: 20.0,
    portfolio_size_units: "1400+ (Regional/Global)",
    portfolio_value_aed: "Institutional Portfolio",
    years_in_business: "10",
    preferred_locations: "Downtown, Business Bay, Dubai Marina, JLT, Palm Jumeirah",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly",
    strengths_tags: "Global Brand, Multi-Channel Distribution, Tech-Driven Property Operations, Experienced Team",
    company_profile: "A globally recognized short-term management entity with highly automated logistics, localized multi-lingual support, and expansive multi-channel property listing syndication.",
  },
  {
    operator_id: "key_view_dubai",
    name: "Key View Dubai",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "800+",
    portfolio_value_aed: "High-Volume Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Dubai Marina, JBR, Downtown, Business Bay, JLT, Sports City",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly",
    strengths_tags: "High Guest Turnover, Aggressive Pricing, Mass Market Footprint, High Occupancy",
    company_profile: "Optimized to maximize high-density tourist locations and entry-level to mid-tier apartment units with aggressive multi-platform pricing algorithms.",
  },
  {
    operator_id: "silkhaus",
    name: "Silkhaus",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "20%",
    min_commission: 20.0,
    max_commission: 20.0,
    portfolio_size_units: "Growing Corporate",
    portfolio_value_aed: "VC Backed Scaling",
    years_in_business: "Tech Startup Era",
    preferred_locations: "DIFC, Downtown, Business Bay, Dubai Marina",
    optimal_bedroom_types: "1BR, 2BR, Studio",
    payout_cycle_day: "Monthly",
    strengths_tags: "Corporate Travel Focus, Hybrid Stays, High Mid-Term Yields, Tech Infrastructure",
    company_profile: "Tech-optimized property group backed by institutional venture capital. Targets corporate business travelers with an integrated framework for seamless short-term and mid-term stays.",
  },
  {
    operator_id: "elite_lux_holiday_homes",
    name: "Elite LUX Holiday Homes",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "25%-30%",
    min_commission: 25.0,
    max_commission: 30.0,
    portfolio_size_units: "Boutique Niche",
    portfolio_value_aed: "Ultra-Luxury Ultra-HNW",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah (Villas), Jumeirah Bay Island, Emirates Hills",
    optimal_bedroom_types: "4BR, 5BR, 6BR+, Luxury Mansions, Private Villas",
    payout_cycle_day: "Custom Portfolio Terms",
    strengths_tags: "VIP Concierge, Strict Guest Screening, Elite Asset Protection, High Nightly Rates",
    company_profile: "Exclusively focused on high-net-worth property owners with ultra-luxury villas. Higher commission compensates for 24/7 dedicated on-site stewards and strict screening models.",
  },
  {
    operator_id: "haus_and_haus_holidays",
    name: "haus & haus Holidays",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "20%",
    min_commission: 20.0,
    max_commission: 20.0,
    portfolio_size_units: "Boutique Curated",
    portfolio_value_aed: "Premium Community Scale",
    years_in_business: "Established Entity",
    preferred_locations: "Dubai Hills Estate, Palm Jumeirah, Downtown, Arabian Ranches",
    optimal_bedroom_types: "2BR, 3BR, Villas, Townhouses",
    payout_cycle_day: "Monthly",
    strengths_tags: "Brokerage Ecosystem, Client Cross-Selling, Premium Visual Styling, Community Experts",
    company_profile: "The dedicated short-term arm of a major award-winning Dubai real estate agency, leveraging a massive existing database of property buyers, tenants, and international investors.",
  },
  {
    operator_id: "airdxb",
    name: "AirDXB",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "16.75%",
    min_commission: 16.75,
    max_commission: 16.75,
    portfolio_size_units: "Mid-Large Portfolio",
    portfolio_value_aed: "Premium Local Assets",
    years_in_business: "Established Local",
    preferred_locations: "Dubai Marina, Palm Jumeirah, JBR, Downtown",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly",
    strengths_tags: "Asset Protection, Local Operational Nuance, Detailed Upkeep, Tailored Tiers",
    company_profile: "Highly respected local operator prioritizing rigorous property preservation, customizable management packages, and high-touch landlord communication.",
  },
  {
    operator_id: "ease_by_emaar",
    name: "Ease by Emaar",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "Developer Managed",
    portfolio_value_aed: "Emaar Ecosystem",
    years_in_business: "Developer Product",
    preferred_locations: "Downtown Dubai, Dubai Creek Harbour, Emaar South, Dubai Hills",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly",
    strengths_tags: "Developer Integration, Building Access Priority, In-Community Perks, Emaar Brand Power",
    company_profile: "An operator directly owned and integrated by Emaar, providing unique benefits like seamless access cards, integrated community app support, and unmatched destination exposure.",
  },
  {
    operator_id: "betterhomes_holiday_homes",
    name: "Betterhomes Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina, Palm",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina, Palm. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "espace_real_estate_vacation_rentals",
    name: "Espace Real Estate Vacation Rentals",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Dubai Hills, Palm, Marina, Meadows",
    optimal_bedroom_types: "Villas, Townhouses, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Dubai Hills, Palm, Marina, Meadows. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "stonetree_vacation_homes",
    name: "Stonetree Vacation Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Business Bay, JLT",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Business Bay, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "allsopp_and_allsopp_holiday_homes",
    name: "Allsopp & Allsopp Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown, Jge, Dubai Hills",
    optimal_bedroom_types: "Studio, 1BR, 2BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown, Jge, Dubai Hills. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "dandb_holiday_homes",
    name: "D&B Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Creek Harbour, Downtown, Meydan",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Creek Harbour, Downtown, Meydan. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "fam_living",
    name: "FAM Living",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "City Walk, Downtown, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across City Walk, Downtown, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "provident_estate_holiday_homes",
    name: "Provident Estate Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Palm Jumeirah, Downtown",
    optimal_bedroom_types: "1BR, 2BR, 3BR, Luxury Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Palm Jumeirah, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "driven_holiday_homes",
    name: "Driven Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Jumeirah, Marina",
    optimal_bedroom_types: "1BR, 2BR, 3BR, Penthouses",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Jumeirah, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "ax_capital_holiday_homes",
    name: "AX CAPITAL Holiday Homes",
    tier: "Tier 2: Real Estate Backed Division",
    est_commission_pct: "18%-22%",
    min_commission: 18.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, Downtown, Marina",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Real Estate Database, Brokerage Ecosystem, Strong Cross-Selling, Institutional Landlords",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, Downtown, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "staybetterdxb",
    name: "StayBetterDXB",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR, Downtown",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "maison_prive",
    name: "Maison Prive",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Marina, Downtown",
    optimal_bedroom_types: "2BR, 3BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "vacationer",
    name: "Vacationer",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Jumeirah, Marina",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Jumeirah, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "suiteable",
    name: "Suiteable",
    tier: "Tier 1: Institutional Market Leader",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, Downtown, JLT",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, Downtown, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "luxury_bookings_dubai",
    name: "Luxury Bookings Dubai",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Jumeirah Bay, Emirates Hills",
    optimal_bedroom_types: "Villas, Mansions, Penthouses",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Jumeirah Bay, Emirates Hills. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "the_holiday_home_co",
    name: "The Holiday Home Co.",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Jumeirah, Palm, Downtown",
    optimal_bedroom_types: "Design Villas, Penthouses",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Jumeirah, Palm, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "bespoke_residences",
    name: "Bespoke Residences",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Marina",
    optimal_bedroom_types: "Luxury Apartments, Serviced Suites",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "prado_living",
    name: "Prado Living",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Dubai Hills",
    optimal_bedroom_types: "Private Estates, Luxury Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Dubai Hills. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "plush_vacation_homes",
    name: "Plush Vacation Homes",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina, Jumeirah",
    optimal_bedroom_types: "Design Condos, Premium 2BR+",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina, Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "palatial_stays",
    name: "Palatial Stays",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Emirates Hills, Jumeirah Bay",
    optimal_bedroom_types: "Mansions, Ultra-Luxury Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Emirates Hills, Jumeirah Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "ultimate_luxury_stays_dubai",
    name: "Ultimate Luxury Stays Dubai",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah",
    optimal_bedroom_types: "Mansion Estates, Beachfront Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "vivant_stays",
    name: "Vivant Stays",
    tier: "Tier 3: Specialized Luxury Boutique",
    est_commission_pct: "20%-30%",
    min_commission: 20.0,
    max_commission: 30.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "Boutique Design 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Luxury Concierge, High Nightly Rates, Ultra-HNW Clients, Strict Guest Screening",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "astatine_holiday_homes",
    name: "Astatine Holiday Homes",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Marina, Silicon Oasis",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Marina, Silicon Oasis. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "black_forest_vacation_homes",
    name: "Black Forest Vacation Homes",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, JLT, Barsha",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, JLT, Barsha. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "happy_season_holiday_homes",
    name: "Happy Season Holiday Homes",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Sports City, IMPZ",
    optimal_bedroom_types: "Studio, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Sports City, IMPZ. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "welcome_home_dubai",
    name: "Welcome Home Dubai",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JBR, Marina, Downtown",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across JBR, Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "higuests_dubai",
    name: "HiGuests Dubai",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "bnbme_holiday_homes",
    name: "Bnbme Holiday Homes",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Palm, Jumeirah",
    optimal_bedroom_types: "1BR, 2BR, 3BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Palm, Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "dream_inn_dubai",
    name: "Dream Inn Dubai",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, City Walk",
    optimal_bedroom_types: "Premium 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, City Walk. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "roami_dubai",
    name: "Roami Dubai",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Business Bay",
    optimal_bedroom_types: "Corporate Units, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "manzil_hospitality",
    name: "Manzil Hospitality",
    tier: "Tier 4: Mid-Scale / Corporate Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Jumeirah, Creek",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Mid-Scale Management, High Volume Stability, Multi-Channel Syndication",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Jumeirah, Creek. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "marina_holiday_homes",
    name: "Marina Holiday Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Dubai Marina, JBR",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Dubai Marina, JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "palm_living_stays",
    name: "Palm Living Stays",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah",
    optimal_bedroom_types: "Apartments, Beach Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "jbr_vacation_rentals",
    name: "JBR Vacation Rentals",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JBR",
    optimal_bedroom_types: "1BR, 2BR, 3BR, 4BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "blue_ocean_holiday_homes",
    name: "Blue Ocean Holiday Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Bluewaters",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Bluewaters. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "skyline_stays_dubai",
    name: "Skyline Stays Dubai",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JLT, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JLT, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "ocean_view_holiday_homes",
    name: "Ocean View Holiday Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JBR, Marina",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across JBR, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "city_premiere_vacation_homes",
    name: "City Premiere Vacation Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, Downtown",
    optimal_bedroom_types: "Serviced Apartments, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "elite_royal_apartments",
    name: "Elite Royal Apartments",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina",
    optimal_bedroom_types: "Premium 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "bella_vista_holiday_homes",
    name: "Bella Vista Holiday Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "white_and_co_holiday_homes",
    name: "White & Co. Holiday Homes",
    tier: "Tier 5: Coastal & Destination Specialist",
    est_commission_pct: "15%-22%",
    min_commission: 15.0,
    max_commission: 22.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Palm Jumeirah",
    optimal_bedroom_types: "Studio, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Coastal Specialists, Beachfront Curation, Tourist Demand Dominant",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Palm Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "burj_living_stays",
    name: "Burj Living Stays",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown Dubai",
    optimal_bedroom_types: "Burj Views, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Downtown Dubai. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "downtown_retreats_dubai",
    name: "Downtown Retreats Dubai",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown Dubai",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Downtown Dubai. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "boulevard_vacation_homes",
    name: "Boulevard Vacation Homes",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown Dubai",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Downtown Dubai. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "metropolitan_living_dubai",
    name: "Metropolitan Living Dubai",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, JLT",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "urban_stays_dubai",
    name: "Urban Stays Dubai",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Business Bay, Marina",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Business Bay, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "capital_comfort_holiday_homes",
    name: "Capital Comfort Holiday Homes",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, DIFC",
    optimal_bedroom_types: "Corporate Studios, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, DIFC. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "executive_stay_dubai",
    name: "Executive Stay Dubai",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "DIFC, Business Bay",
    optimal_bedroom_types: "1BR, 2BR Corporate",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across DIFC, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "difc_premier_holiday_homes",
    name: "DIFC Premier Holiday Homes",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "DIFC",
    optimal_bedroom_types: "Corporate 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across DIFC. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "business_bay_vacation_rentals",
    name: "Business Bay Vacation Rentals",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "corporate_keys_dubai",
    name: "Corporate Keys Dubai",
    tier: "Tier 6: Downtown & Urban Specialist",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "DIFC, Business Bay, Downtown",
    optimal_bedroom_types: "Corporate Studios, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "Corporate Travel Focus, DIFC/Downtown Dominant, Business Amenities",
    company_profile: "Licensed operator specializing in short-term management options across DIFC, Business Bay, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "keysplease_holiday_homes",
    name: "Keysplease Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Palm, JBR",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Palm, JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "one_perfect_stay",
    name: "One Perfect Stay",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "zayan_holiday_homes",
    name: "Zayan Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "saffron_holiday_homes",
    name: "Saffron Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Deira, Bur Dubai, Silicon Oasis",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Deira, Bur Dubai, Silicon Oasis. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "key_one_holiday_homes",
    name: "Key One Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JLT",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "vasco_holiday_homes",
    name: "Vasco Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "aura_living_dubai",
    name: "Aura Living Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "golden_choice_holiday_homes",
    name: "Golden Choice Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Al Barsha, JLT",
    optimal_bedroom_types: "Studio, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Al Barsha, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "homecheck_dubai",
    name: "HomeCheck Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "Property Audits, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "sonder_dubai",
    name: "Sonder Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Business Bay, Marina",
    optimal_bedroom_types: "Sonder Tech Units, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Business Bay, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "staycae_holiday_homes",
    name: "Staycae Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, Al Barsha",
    optimal_bedroom_types: "Studio, 1BR, 2BR Serviced",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, Al Barsha. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "stallion_holiday_homes",
    name: "Stallion Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Sports City",
    optimal_bedroom_types: "Studio, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Sports City. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "superhost_dubai",
    name: "Superhost Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR, Downtown",
    optimal_bedroom_types: "High-Yield Studios, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "nest_vacation_homes",
    name: "Nest Vacation Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Marina",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "oyo_home_dubai",
    name: "Oyo Home Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Silicon Oasis, Sports City, JLT",
    optimal_bedroom_types: "Budget Studios, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Silicon Oasis, Sports City, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "short_term_stays_dubai",
    name: "Short Term Stays Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "city_stay_holiday_homes",
    name: "City Stay Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Al Barsha, Business Bay",
    optimal_bedroom_types: "Standard 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Al Barsha, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "your_base_dubai",
    name: "Your Base Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, JLT",
    optimal_bedroom_types: "Studio, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "yanjoon_holiday_homes",
    name: "Yanjoon Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JBR, Marina",
    optimal_bedroom_types: "Beach Apartments, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JBR, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "top_class_holiday_homes",
    name: "Top Class Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JLT",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "indubai_holiday_homes",
    name: "InDubai Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "knightsbridge_holiday_homes",
    name: "Knightsbridge Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Jumeirah",
    optimal_bedroom_types: "Premium 1BR, 2BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "royal_club_holiday_homes",
    name: "Royal Club Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah",
    optimal_bedroom_types: "Shoreline Apartments, 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "aura_holiday_homes",
    name: "Aura Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, Downtown",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "posh_stays_dubai",
    name: "Posh Stays Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina",
    optimal_bedroom_types: "Premium 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "safe_haven_vacation_rentals",
    name: "Safe Haven Vacation Rentals",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JLT, Sports City",
    optimal_bedroom_types: "Studio, 1BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JLT, Sports City. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "maple_holiday_homes",
    name: "Maple Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, JLT",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "smart_stay_dubai",
    name: "Smart Stay Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "regal_holiday_homes",
    name: "Regal Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Business Bay",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "signature_holiday_homes",
    name: "Signature Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Palm, Downtown",
    optimal_bedroom_types: "Premium Apartments, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Palm, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "prime_stay_dubai",
    name: "Prime Stay Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JLT, Business Bay",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JLT, Business Bay. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "elite_choice_holiday_homes",
    name: "Elite Choice Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "JBR, Marina",
    optimal_bedroom_types: "1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across JBR, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "my_dubai_stay",
    name: "My Dubai Stay",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, JBR, Downtown",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, JBR, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "bnb_dubai",
    name: "BNB Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "simply_comfort_holiday_homes",
    name: "Simply Comfort Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Marina",
    optimal_bedroom_types: "Beachfront 1BR, 2BR, 3BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "key_to_dubai",
    name: "Key To Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "live_large_holiday_homes",
    name: "Live Large Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Palm Jumeirah, Marina",
    optimal_bedroom_types: "Large 2BR, 3BR, Villas",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Palm Jumeirah, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "elite_escapes_dubai",
    name: "Elite Escapes Dubai",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Downtown, Marina",
    optimal_bedroom_types: "Premium 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Downtown, Marina. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "starlight_holiday_homes",
    name: "Starlight Holiday Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Business Bay, JLT",
    optimal_bedroom_types: "Studio, 1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Business Bay, JLT. Fully registered with the Department of Economy and Tourism (DET).",
  },
  {
    operator_id: "aura_vacation_homes",
    name: "Aura Vacation Homes",
    tier: "Tier 7: DET Licensed Independent",
    est_commission_pct: "15%-20%",
    min_commission: 15.0,
    max_commission: 20.0,
    portfolio_size_units: "DTCM Registered Portfolio",
    portfolio_value_aed: "Local Asset Scale",
    years_in_business: "Established",
    preferred_locations: "Marina, Downtown",
    optimal_bedroom_types: "1BR, 2BR",
    payout_cycle_day: "Monthly standard",
    strengths_tags: "DET/DTCM Licensed, Local Independent, Competitive Base Management",
    company_profile: "Licensed operator specializing in short-term management options across Marina, Downtown. Fully registered with the Department of Economy and Tourism (DET).",
  },
];

/**
 * Returns all operators from CSV database
 * Can be used for advanced filtering and matching
 */
export function getAllOperatorsFromCSV(): OperatorCSVData[] {
  return OPERATOR_CSV_DATA;
}

/**
 * Filter operators by tier
 */
export function filterOperatorsByTier(tier: string): OperatorCSVData[] {
  return OPERATOR_CSV_DATA.filter(op => op.tier.includes(tier));
}

/**
 * Filter operators by location
 */
export function filterOperatorsByLocation(location: string): OperatorCSVData[] {
  return OPERATOR_CSV_DATA.filter(op =>
    op.preferred_locations.toLowerCase().includes(location.toLowerCase())
  );
}

/**
 * Filter operators by bedroom type
 */
export function filterOperatorsByBedroomType(type: string): OperatorCSVData[] {
  return OPERATOR_CSV_DATA.filter(op =>
    op.optimal_bedroom_types.toLowerCase().includes(type.toLowerCase())
  );
}
