import { NextResponse } from "next/server";
import { Resend } from "resend";

export const dynamic = "force-dynamic";

const FROM = process.env.RESEND_FROM ?? "AssetIntel <hello@assetintel.ae>";
const NOTIFY = process.env.REPORT_NOTIFY_EMAIL ?? "lmoraes55@gmail.com";

interface AgentReportBody {
  email: string;
  agentName?: string;
  agencyName?: string;
  reportType: string;
  property?: string;
  building?: string;
  area?: string;
  summaryHtml: string; // pre-built HTML summary of the report body
  pdfBase64?: string;
  pdfFilename?: string;
}

export async function POST(request: Request) {
  let body: AgentReportBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON" }, { status: 400 });
  }

  const { email, agentName, agencyName, reportType, property, summaryHtml, pdfBase64: rawPdfBase64, pdfFilename } = body;
  if (!email || !summaryHtml) {
    return NextResponse.json({ ok: false, error: "email and summaryHtml are required" }, { status: 400 });
  }

  // Strip data-URL prefix if present. jsPDF's datauristring includes a
  // `;filename=...;` segment before `base64,` -- match up to the FIRST `;base64,`
  // occurrence rather than a single semicolon segment, or the prefix stays stuck
  // onto the file and corrupts it.
  const pdfBase64 = rawPdfBase64 ? rawPdfBase64.replace(/^data:.*?;base64,/, "") : undefined;

  const propertyLabel = property || "the property";

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />
<meta name="color-scheme" content="light"/>
<meta name="supported-color-schemes" content="light"/>
</head>
<body style="margin:0;padding:0;background:#F8F4EE;font-family:system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F8F4EE;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">

        <!-- Light header, not dark-green-with-white-text: Gmail's mobile-app automatic
             dark mode recolors message text unpredictably and isn't reliably
             controllable with [data-ogsc]/[data-ogsb] CSS hooks on iOS -- confirmed
             live, the hook-based fix did not resolve it on a real iOS Gmail app. A
             light background with dark brand-color text has nothing for that
             heuristic to break. -->
        <tr><td bgcolor="#F4F9F7" style="background:#F4F9F7;padding:32px 40px;border-bottom:1px solid #E6E1D8;">
          <p style="margin:0;color:#8B6F3F;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;">AssetIntel · Agent Report</p>
          <h1 style="margin:8px 0 0;color:#1B5E4A;font-size:22px;font-weight:700;font-family:Georgia,serif;">${reportType}</h1>
          <p style="margin:6px 0 0;color:#6B6B6B;font-size:13px;">${propertyLabel}${agencyName ? ` · ${agencyName}` : ""}</p>
        </td></tr>

        <tr><td style="padding:28px 40px;">
          ${summaryHtml}
        </td></tr>

        <tr><td style="padding:0 40px 28px;">
          <p style="margin:16px 0 0;font-size:11px;color:#999;line-height:1.6;">
            AssetIntel reports are generated using available DLD data, rental transaction data, STR assumptions, and user inputs. Reports are indicative and should not be treated as guaranteed investment, financial, legal, or valuation advice. Final purchase, rental, and investment decisions remain the responsibility of the buyer and should be verified with licensed professionals where required.
          </p>
        </td></tr>

        <tr><td style="padding:0 40px 32px;border-top:1px solid #E6E1D8;">
          <p style="margin:24px 0 0;font-size:12px;color:#6B6B6B;line-height:1.6;">
            Generated by <strong>AssetIntel</strong> · <a href="https://assetintel.ae" style="color:#1B5E4A;">assetintel.ae</a>
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;

  const resend = new Resend(process.env.RESEND_API_KEY);
  try {
    await resend.emails.send({
      from: FROM,
      to: [email],
      replyTo: NOTIFY,
      subject: `Your AssetIntel ${reportType} · ${propertyLabel}`,
      html,
      attachments: pdfBase64
        ? [{ filename: pdfFilename || "AssetIntel-Agent-Report.pdf", content: pdfBase64 }]
        : undefined,
    });
    resend.emails.send({
      from: FROM,
      to: [NOTIFY],
      subject: `[Agent Lead] ${reportType} auto-sent to ${email} · ${propertyLabel}`,
      html: `<p>Agent report (${reportType}) auto-emailed to <strong>${email}</strong>${agentName ? ` (${agentName})` : ""}${agencyName ? ` · ${agencyName}` : ""} for <strong>${propertyLabel}</strong>.</p>`,
    }).catch(() => {});
    return NextResponse.json({ ok: true });
  } catch (e) {
    console.error("[SEND-AGENT-REPORT]", (e as Error).message);
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
